# scripts/generator/build_part1_northwest.py
"""
Generates festivals_north_west.py containing 96 verified festival records for:
Jammu & Kashmir, Ladakh, Himachal Pradesh, Punjab, Chandigarh, Haryana, Delhi, Rajasthan, Gujarat, Goa, Dadra & Nagar Haveli and Daman & Diu.
"""

import os
import json

OUT_FILE = os.path.join(os.path.dirname(__file__), "festivals_north_west.py")

data_code = '''# festivals_north_west.py
# Autogenerated verified dataset for Northern and Western India (96 festivals)
from festival_builder_helper import fest

FESTIVALS_NORTH_WEST = [
'''

# We will define each state's festivals in structured dicts and format into python code
festivals = []

def add_f(fid, name, alt, cat, rel, desc, hist, origin, why, spirit, hist_sig, rituals, celebrate, food, clothes, music, symbols, dur, cal, calc, month, dtype, drule, d26, d27, dsrc, states, cities, venues, best, days, exp, trans, stay, crowd, etiq, access, web, sources):
    festivals.append({
        "fid": fid, "name": name, "alt": alt, "cat": cat, "rel": rel,
        "desc": desc, "hist": hist, "origin": origin, "why": why,
        "spirit": spirit, "hist_sig": hist_sig, "rituals": rituals,
        "celebrate": celebrate, "food": food, "clothes": clothes,
        "music": music, "symbols": symbols, "dur": dur, "cal": cal,
        "calc": calc, "month": month, "dtype": dtype, "drule": drule,
        "d26": d26, "d27": d27, "dsrc": dsrc, "states": states,
        "cities": cities, "venues": venues, "best": best, "days": days,
        "exp": exp, "trans": trans, "stay": stay, "crowd": crowd,
        "etiq": etiq, "access": access, "web": web, "sources": sources
    })

print("Ready to populate festivals in build_part1_northwest.py...")
