# scripts/generator/data_central.py
"""
Central India Festivals Master Data (22 Authentic Records)
States Covered:
- Madhya Pradesh (14)
- Chhattisgarh (8)
"""

from data_north import F

FESTIVALS_CENTRAL = [
    # ==================== MADHYA PRADESH (14) ====================
    F(
        "fest-khajuraho-dance-festival", "Khajuraho Dance Festival", ["Khajuraho Nritya Samaroh"],
        "Art & Cultural Festival", "Classical Indian Dance & UNESCO Temple Art",
        "A world-renowned one-week celebration of classical Indian dance staged against the floodlit sandstone facades of the Western Group of Khajuraho Temples.",
        "Initiated in 1975 by the Madhya Pradesh Kala Parishad to celebrate classical performing arts at the 1,000-year-old Chandela dynasty UNESCO monuments.",
        "Celebrates the immortal synthesis of stone sculpture, classical aesthetics, and temple dance.",
        "To promote high classical performing arts and highlight the architectural brilliance of the Chandela temples.",
        "The Western Group of Temples (Chitragupta and Vishwanatha temples) serves as the world's most breathtaking natural temple backdrop for classical dance.",
        "Features leading exponents of Bharatanatyam, Kathak, Odissi, Kuchipudi, Mohiniyattam, and Manipuri dancing under the open night sky.",
        ["Nightly classical dance performances by Padma and Sangeet Natak Akademi awardees", "Craft exhibition 'Hunar' showcasing regional artisans and sculptors", "Interactive morning art dialogues ('Kala Varta') between dancers and critics"],
        "Connoisseurs sit in rapt silence in the cool February night air, watching dancers match the exact sculptural poses carved in stone on the temple behind them.",
        ["Bundelkhandi Thoke", "Mawa Jalebi", "Dal Baati Churma", "Rogan Josh", "Khajuraho Sweet Rabri"],
        "Refined formal ethnic wear: handloom Chanderi and Maheshwari silk sarees, bandhgalas, and elegant shawls.",
        "Sublime classical dance dramas, mridangam and pakhawaj rhythms, classical vocal recitals, and flute melodies.",
        "Intricately carved sandstone temple spires, sculpted celestial nymphs (Surasundaris), and dramatic golden floodlights.",
        "7 Days", "Gregorian / Annual", "February 20 to 26 annually.",
        "February", "FIXED", "Held annually February 20-26.",
        "2026-02-20", "2027-02-20", "Ustad Allauddin Khan Sangeet Evam Kala Akademi & MP Tourism",
        ["Madhya Pradesh"], ["Khajuraho", "Chhatarpur"], ["Western Group of Temples Khajuraho"],
        "Evenings between 6:30 PM and 10 PM during floodlit dance recitals", 3,
        "Transcendental, awe-inspiring aesthetic experience where ancient sculpted sandstone dancers seem to come to life in living rhythm before your eyes.",
        "Khajuraho Airport connects to Delhi/Varanasi; direct railway station; 4-hour highway drive from Jhansi.",
        "Extensive luxury and heritage hotels and boutique resorts across Khajuraho.",
        "Chilly February evenings in open-air auditorium; carry a warm shawl or jacket.",
        "Strict archaeological protection: no touching temple carvings; photography without flash only.",
        web="https://khajurahodancefestival.com"
    ),
    F(
        "fest-tansen-samaroh-gwalior", "Tansen Samaroh Gwalior", ["Tansen Music Festival"],
        "Art & Cultural Festival", "Indian Classical Music / Gwalior Gharana",
        "The oldest and most prestigious classical music festival in India, celebrated at the tomb of musical legend Mian Tansen in Gwalior.",
        "Conceived in the 1930s to honor Mian Tansen, the court musician of Emperor Akbar and one of the Nine Gems (Navaratnas) of Mughal India.",
        "Celebrates the pure, meditative traditions of Hindustani classical vocal and instrumental music.",
        "To honor the father of north Indian classical music and promote the living heritage of the Gwalior Gharana.",
        "Staged directly at the sacred Samadhi of Tansen under the legendary tamarind tree whose leaves were believed to sweeten the singing voice.",
        "Features the prestigious National Tansen Samman award presented to living legends of Indian classical music.",
        ["Nightlong and dawn musical sessions (Baithaks) by celebrated classical maestros", "Performance of classical Dhrupad compositions created by Tansen", "Solemn morning floral offering and prayer at Tansen's tomb and the grave of Sufi saint Muhammad Ghaus"],
        "Music lovers sit cross-legged on white cotton mattresses in the open air, listening to meditative ragas from dusk until the early hours of dawn.",
        ["Gwalior Bedai with spicy potato curry", "Kachori", "Morena Gajak", "Gwalior Jalebi", "Rabri"],
        "Traditional formal attire: fine white Kurtas, Nehru jackets, Pashmina shawls, and classical silk sarees.",
        "Pure classical Dhrupad, Khayal, Sitar, Sarod, Rudra Veena, and subtle Tabla-Pakhawaj accompaniment.",
        "Mughal-style stone mausoleum of Tansen, ancient tamarind tree, Tanpura string instruments, and white cotton shamianas.",
        "5 Days", "Gregorian / Winter", "Held in December annually.",
        "December", "ORGANIZER_ANNOUNCED", "Organized annually in December by Ustad Allauddin Khan Sangeet Akademi.",
        "2026-12-19", "2027-12-18", "MP Culture Department & Gwalior District Administration",
        ["Madhya Pradesh"], ["Gwalior"], ["Tomb of Tansen Hazira Gwalior", "Gwalior Fort"],
        "Evening baithaks (6 PM to 10 PM) and the serene Sunday morning dawn session (9 AM)", 3,
        "Deeply sacred, acoustically pure musical pilgrimage where centuries-old classical melodies echo beneath the stars at the master's resting place.",
        "Gwalior Airport and major North-Central railway junction on the Delhi-Mumbai line.",
        "Heritage palace hotels and modern business hotels across Gwalior.",
        "Cold December nights; heavy woolens, shawls, and insulated caps essential for open-air sessions.",
        "Strict classical concert etiquette: maintain silence during performances; do not walk around during raga alaap.",
        web="https://mptourism.com"
    ),
    F(
        "fest-lokrang-festival-bhopal", "Lokrang Festival Bhopal", ["Bhopal National Folk Festival"],
        "Art & Cultural Festival", "Tribal, Folk & Indigenous Heritage",
        "A spectacular five-day national cultural festival organized in the City of Lakes, bringing together over 1,000 tribal and folk artists from across India.",
        "Initiated on Republic Day in 1986 by the Directorate of Culture, Madhya Pradesh, to preserve and celebrate India's indigenous tribal arts.",
        "Celebrates India's rich cultural diversity, tribal heritage, and the living arts of indigenous communities.",
        "To provide a prominent urban platform for remote tribal artists and foster cross-cultural understanding.",
        "Staged on the open-air cultural grounds of Ravindra Bhavan, overlooking the tranquil upper lake of Bhopal.",
        "Features five distinct components: folk dance, tribal music, indigenous pottery and crafts, children's folk theatre, and traditional tribal cuisine.",
        ["Grand Republic Day evening cultural inauguration featuring 28 state folk dance contingents", "Tribal craft and live pottery demonstrations by national award winners", "Regional food festival showcasing indigenous tribal delicacies from across India"],
        "Visitors explore bustling craft alleys, watch thrilling folk acrobats and masked dancers, and taste authentic tribal dishes cooked over wood fires.",
        ["Bhopali Biryani", "Bafla (boiled and baked wheat balls with spicy dal)", "Mawa Baati", "Bhopali Paan", "Poha Jalebi"],
        "Smart casuals, handloom stoles, ethnic kurtas, and traditional tribal textiles.",
        "Energetic tribal dances: Gond Karma, Baiga Pardhauni, Bhil Bhagoria, alongside folk dances from every Indian state.",
        "Tribal mud mural motifs, painted terracotta horses, bamboo pavilions, and illuminated stage sets.",
        "5 Days", "Gregorian / Annual", "January 26 to 30 annually.",
        "January", "FIXED", "Held annually January 26-30 starting on Republic Day.",
        "2026-01-26", "2027-01-26", "Adivasi Lok Kala Evam Boli Vikas Akademi & MP Culture",
        ["Madhya Pradesh"], ["Bhopal"], ["Ravindra Bhavan Open Air Complex Bhopal"],
        "Evenings between 5:30 PM and 9:30 PM for main stage folk dance performances", 2,
        "Vibrant, colorful celebration of India's indigenous soul, filled with earth-shaking tribal drum rhythms, colorful feathers, and warm hospitality.",
        "Easily accessible across Bhopal via auto-rickshaws, cabs, and city buses.",
        "Extensive hotels and heritage properties overlooking Bhopal's Upper Lake.",
        "Pleasant winter evenings; carry a light jacket.",
        "Support indigenous tribal artists by purchasing authentic handmade terracotta, brass Dhokra, and Gond paintings directly.",
        web="https://mptourism.com"
    ),
    F(
        "fest-ujjain-simhastha-kumbh", "Ujjain Simhastha Kumbh Mela", ["Ujjain Maha Kumbh"],
        "Spiritual & Temple", "Hinduism (Jyotirlinga & Sacred Confluence)",
        "The colossal celestial congregation held every 12 years on the banks of the holy Kshipra River at the sacred city of Lord Mahakaleshwar.",
        "Celebrated since ancient Vedic times, sanctified as the city of the Greenwich of ancient Indian astronomy (Prime Meridian of Avantika).",
        "Celebrates the planetary alignment when Jupiter enters Leo (Simha) and the Sun enters Aries (Mesha).",
        "To take the holy Shahi Snan (royal bath) in the sacred Kshipra River and seek liberation at the Mahakaleshwar Jyotirlinga.",
        "One of the four sacred Kumbh Melas of India, uniquely celebrated in the sacred city of Mahakal where Lord Shiva is the eternal king.",
        "Draws over 75 million pilgrims, ascetics of thirteen Akharas, and spiritual masters during its month-long observance.",
        ["Grand Shahi Snan royal bathing processions of Naga sadhus into the Kshipra River at Ram Ghat", "Midnight Bhasma Aarti at the sanctified Mahakaleshwar Jyotirlinga temple", "Continuous religious discourses, Annakshetras serving free food, and evening Kshipra Aarti"],
        "Ram Ghat and Dutt Akhara ghats turn into an awe-inspiring sea of faith, with millions chanting 'Jai Mahakal' as sacred waters splash under the sun.",
        ["Ujjaini Poha Jalebi", "Dal Baati Churma", "Malpua", "Sabudana Khichdi", "Badaam Milk"],
        "Simple saffron and white cotton dhotis, ascetic robes, Rudraksha malas, and modest pilgrim attire.",
        "Thunderous conch shell blasts, metal damaru drums, brass bells, and roaring Shaivite chants of 'Har Har Mahadev'.",
        "Sacred Kshipra River ghats, Ram Ghat temples, Mahakaleshwar golden spire, and Akhara trident flags.",
        "1 Month", "Astrological / 12-Year Cycle", "Jupiter in Leo and Sun in Aries (April - May every 12 years)",
        "April - May", "LUNISOLAR", "Occurs every 12 years (next in 2028).",
        "2028-04-09", "2028-05-08", "Ujjain Simhastha Mela Authority & Government of Madhya Pradesh",
        ["Madhya Pradesh"], ["Ujjain"], ["Ram Ghat Kshipra River", "Mahakaleshwar Temple", "Dutt Akhara"],
        "Dawn of designated Shahi Snan dates and evening Kshipra Aarti at Ram Ghat", 4,
        "Overwhelming spiritual magnitude, ancient ascetic traditions, vibrant sacred riverbanks, and profound communion with the divine energy of Mahakal.",
        "Ujjain Junction is a major railway station; Indore Airport is 55 km away with 4-lane highway connectivity.",
        "Massive tented pop-up cities, ashrams, and hotels; advance booking essential during Simhastha years.",
        "Monumental crowds exceeding 10 million on royal bathing days; follow police crowd movement routes strictly.",
        "Remove footwear before stepping onto bathing ghats; bathe strictly within safety barricades.",
        web="https://ujjain.nic.in"
    ),
    F(
        "fest-bhagoria-tribal-fair", "Bhagoria Tribal Fair Jhabua & Alirajpur", ["Bhagoria Haat Mahotsav"],
        "Tribal & Folk Traditions", "Bhil & Bhilala Indigenous Heritage",
        "An exhilarating tribal festival of spring romance, matchmaking, and harvest joy celebrated across the weekly rural haats of Jhabua and Alirajpur.",
        "Centuries-old indigenous festival of the Bhil, Bhilala, and Pateliya tribal communities, marking the conclusion of the agricultural harvest before Holi.",
        "Celebrates youth, romance, harvest bounty, and thanksgiving to nature.",
        "Traditionally serves as a joyous social carnival where young tribal men and women meet, express affection, and choose life partners.",
        "Famous for the traditional courting ritual: a youth offers red betel leaf (Paan) to a maiden, and if she accepts, they celebrate their union.",
        "Features thrilling traditional wooden Ferris wheels, dynamic tribal flute orchestras, and rhythmic community dances.",
        ["Brisk morning trading of silver jewelry, farming tools, and colorful clothing at the weekly haat", "Young tribal men playing massive hollow bamboo flutes and playing traditional wooden drums", "Joyful rides on manually operated wooden giant wheels and savouring sweet jalebis"],
        "Tribal youth dress in striking matching outfits, wandering through the dusty rural markets in laughing groups, playing flutes and dancing.",
        ["Giant Jalebis (weighing up to 500 grams each)", "Makki Ki Roti with Garlic Chutney", "Mahua beverage (traditional sacred brew)", "Pani Puri"],
        "Dazzling tribal finery: women wear neon-bright Lehengas with heavy silver necklaces and armlets; men wear colorful shirts, turbans, and carry flutes and bows.",
        "Hypnotic, continuous drone of giant bamboo flutes, accompanied by thundering beats of wooden Mandal drums.",
        "Carved bamboo flutes, giant wooden Ferris wheels, mounds of giant golden jalebis, and tribal silver jewelry.",
        "7 Days (at rotating village haats)", "Hindu Lunisolar / Spring", "Held during the seven days immediately preceding Holi.",
        "March", "LUNISOLAR", "Held during the week leading up to Holi in Phalguna.",
        "2026-02-25", "2027-03-16", "Jhabua & Alirajpur District Administrations & MP Tourism",
        ["Madhya Pradesh"], ["Jhabua", "Alirajpur", "Bhabhra", "Ranapur"], ["Village Haat Grounds across Jhabua and Alirajpur"],
        "Daytime between 10 AM and 4 PM when the tribal haat reaches peak festive energy", 2,
        "Authentic, infectious tribal joy, dazzling neon colors, hypnotic flute melodies echoing across rural landscapes, and uninhibited celebration of life.",
        "150 km from Indore (3 hours by road via Dhar); accessible by highway buses and private cars.",
        "Simple guesthouses in Jhabua or base yourself in Indore and visit on day excursions.",
        "Crowded and dusty rural market conditions; wear comfortable clothing and flat walking shoes.",
        "Respect the cultural modesty of tribal youth; do not intrude on personal courting interactions; take photos only with polite consent.",
        web="https://jhabua.nic.in"
    ),
    F(
        "fest-mandu-festival", "Mandu Festival", ["City of Joy Heritage Festival"],
        "Historical & Royal", "Secular / Afghan Architecture & Romance",
        "A charming five-day festival celebrating the architectural romance, medieval Afghan monuments, and scenic plateau of Mandu (the City of Joy).",
        "Initiated by Madhya Pradesh Tourism to celebrate the immortal love story of Sultan Baz Bahadur and Rani Roopmati amidst the dramatic 15th-century ruins.",
        "Celebrates Mandu's rich medieval Islamic and Afghan architectural heritage and royal courtly romance.",
        "To promote heritage tourism, hot air ballooning, and eco-adventure in one of India's most dramatic medieval ruined cities.",
        "Set against the miraculous Jahaz Mahal (Ship Palace), floating between two artificial lakes, and the cliffside pavilion of Rani Roopmati.",
        "Features hot air balloon flights at sunrise, cycling tours across ancient palaces, and classical-Sufi concerts at night.",
        ["Hot air balloon flights over the medieval ruined palaces at dawn", "Heritage cycling tours through the ancient stone gateways (Darwazas) and baolis", "Nightly Sufi and classical musical concerts inside illuminated medieval courtyards"],
        "Visitors explore dramatic ruined palaces shrouded in morning mist, climb to Roopmati's Pavilion overlooking the Narmada River, and attend moonlit concerts.",
        ["Mandu Tamarind (giant Baobab fruit pulp drinks)", "Dal Bafla", "Malwa Poha", "Jalebi", "Bhutte Ka Kees"],
        "Smart casuals, comfortable walking boots, warm evening jackets, and light ethnic stoles.",
        "Soulful Sufi Qawwalis, classical flute recitals, Kabir rock fusion, and traditional Malwa folk music.",
        "Jahaz Mahal stone arches, giant Baobab trees, Roopmati's cliffside pavilion, and colorful hot air balloons.",
        "5 Days", "Gregorian / Winter", "Held in December / January annually.",
        "December - January", "ORGANIZER_ANNOUNCED", "Announced annually by MP Tourism.",
        "2026-12-28", "2027-12-28", "Madhya Pradesh Tourism Board (MPTB)",
        ["Madhya Pradesh"], ["Mandu (Mandav)", "Dhar"], ["Jahaz Mahal Complex", "Roopmati Pavilion", "Hindola Mahal"],
        "Sunrise for hot air ballooning and evening 6 PM onwards for illuminated palace concerts", 2,
        "Romantic, poetic medieval atmosphere with misty hilltop ruins, dramatic cliffs dropping into the Narmada valley, and soulful Sufi melodies.",
        "95 km from Indore Airport (2.5-hour scenic drive via Dhar); accessible by taxi or tourist bus.",
        "Luxury glamping tented city set up by MP Tourism, heritage hotels, and boutique resorts in Mandu.",
        "Cobbled stone pathways and undulating plateau; wear sturdy comfortable walking shoes.",
        "Respect the historic monuments; hot air balloon rides require advance online booking due to limited seats.",
        web="https://mandufestival.com"
    ),
    F(
        "fest-pachmarhi-utsav", "Pachmarhi Utsav", ["Queen of Satpura Cultural Festival"],
        "Seasonal & Nature", "Secular / Hill Station Ecology & Folk Arts",
        "A delightful year-end cultural festival celebrated in the lush forested hill station of Pachmarhi amidst cascading waterfalls and colonial bungalows.",
        "Established by the Madhya Pradesh Tourism Board to celebrate the winter season in the state's sole hill station.",
        "Celebrates the pristine biodiversity of the Satpura Tiger Reserve, British colonial heritage, and indigenous Gond-Korku tribal culture.",
        "To provide a vibrant cultural retreat for travelers during the year-end holidays.",
        "Set in an idyllic valley at 3,500 feet, surrounded by deep sandstone ravines, ancient rock paintings, and sal forests.",
        "Features a colorful crafts bazaar, national folk dance performances, and adventure sports like paragliding and rock climbing.",
        ["Evening cultural concerts showcasing folk dances from across India", "Artisan crafts fair featuring Gond tribal paintings, bamboo crafts, and wild forest honey", "Guided nature walks to historic viewpoints like Dhoopgarh (highest peak in MP) and Bee Falls"],
        "Visitors enjoy the pleasant mountain chill, strolling past colonial sandstone churches, exploring prehistoric cave paintings, and attending evening shows.",
        ["Bhutta (roasted sweet corn)", "Dal Bafla", "Satpura Honey pancakes", "Poha Jalebi", "Garam Masala Tea"],
        "Winter woolens: warm jackets, colorful scarves, woolen caps, and comfortable hiking attire.",
        "Tribal Gond and Korku folk dances, classical dance dramas, and live acoustic fusion bands.",
        "Dhoopgarh mountain sunset, sandstone gorge cliffs, green pine forests, and open-air festival stage.",
        "5 Days", "Gregorian / Year-End", "December 26 to 30 annually.",
        "December", "FIXED", "Held annually December 26-30.",
        "2026-12-26", "2027-12-26", "Madhya Pradesh Tourism Board & Pachmarhi Special Area Development Authority",
        ["Madhya Pradesh"], ["Pachmarhi", "Narmadapuram (Hoshangabad)"], ["Pachmarhi Golf Course Grounds", "Dhoopgarh"],
        "Sunset at Dhoopgarh followed by evening cultural concerts at the festival ground", 2,
        "Refreshing mountain chill, fragrant pine and sal forests, dramatic sunset viewpoints, and lively folk entertainment under starry skies.",
        "47 km from Pipariya Railway Station (on Mumbai-Howrah mainline); easily reached by taxis and buses.",
        "Colonial heritage bungalows, MP Tourism resorts, and private hotels across Pachmarhi.",
        "Cold winter evenings (temperatures can drop to 3°C); carry adequate warm woolen layers.",
        "Eco-sensitive biosphere reserve: plastic littering is strictly penalized; do not disturb wildlife in forest zones.",
        web="https://mptourism.com"
    ),
    F(
        "fest-chethiyagiri-vihara-sanchi", "Chethiyagiri Vihara Festival Sanchi", ["Sanchi International Buddhist Festival"],
        "Spiritual & Temple", "Buddhism (Theravada / Sacred Relics)",
        "The sacred international Buddhist pilgrimage where the holy bone relics of the Buddha's chief disciples, Sariputta and Mahamoggallana, are displayed.",
        "Initiated in 1952 when the sacred relics of Sariputta and Mahamoggallana (discovered by Sir Alexander Cunningham in 1851) were returned from London and enshrined.",
        "Commemorates the enshrinement of the holy relics and honors the foremost disciples of the Buddha.",
        "To venerate the holy relics, seek spiritual wisdom, and celebrate universal Buddhist peace and compassion.",
        "Attracts Buddhist monks, ambassadors, and pilgrims from Sri Lanka, Myanmar, Japan, Thailand, Cambodia, and Tibet.",
        "The sacred golden and crystal caskets containing the bone relics are brought out of the sanctum vault for public darshan once a year.",
        ["Ceremonial exposition of the holy bone relics of Arahat Sariputta and Arahat Mahamoggallana", "Chanting of the Dhammacakkappavattana Sutta and Karaniya Metta Sutta by international monks", "Solemn circumambulation of the Great Stupa of Sanchi (UNESCO World Heritage Site)"],
        "Monks in golden, saffron, and crimson robes lead peaceful walking processions around the ancient 3rd-century BCE stone stupa of Emperor Ashoka.",
        ["Sattvic vegetarian feast meals", "Sri Lankan hoppers and tea", "Kheer", "Fruit prasad"],
        "Monastic robes of various Buddhist lineages, alongside crisp white cotton pilgrim clothing.",
        "Deep meditative Buddhist Pali chanting, temple bells, and gentle gong strikes.",
        "Great Stupa of Sanchi with carved Torana gateways, crystal relic casket, and fluttering five-colored Buddhist flags.",
        "2 Days", "Gregorian / Autumn", "Last weekend of November annually.",
        "November", "FIXED", "Last Saturday and Sunday of November.",
        "2026-11-28", "2027-11-27", "Maha Bodhi Society of India & MP Culture Department",
        ["Madhya Pradesh"], ["Sanchi", "Raisen", "Bhopal"], ["Chethiyagiri Vihara", "Great Stupa of Sanchi"],
        "Morning relic exposition ceremony at 9 AM and peaceful sunset meditation at the Great Stupa", 2,
        "Profound, tearful spiritual tranquility, gentle monks chanting under the Bodhi tree, and timeless monumental Mauryan stone architecture.",
        "46 km northeast of Bhopal on the mainline railway; easily reached by highway taxi or local train to Sanchi station.",
        "Buddhist pilgrim guesthouses at the Maha Bodhi Society, MP Tourism Gateway Retreat, and hotels in Bhopal.",
        "Remove footwear before climbing the stupa terraces; maintain respectful silence around meditating monks.",
        "Do not lean against or touch delicate 2,000-year-old carved sandstone gateway sculptures.",
        web="https://mptourism.com"
    ),
    F(
        "fest-malwa-utsav", "Malwa Utsav Indore & Ujjain", ["Malwa Cultural & Food Festival"],
        "Art & Cultural Festival", "Malwa Regional Heritage & Culinary Arts",
        "A grand celebration of the culture, folk dances, and legendary street food of the fertile Malwa plateau, held in Indore and Ujjain.",
        "Established by Madhya Pradesh Tourism to showcase the rich cultural traditions, handicrafts, and culinary heritage of the Malwa region.",
        "Celebrates the peace, prosperity, and agrarian abundance nurtured by the historic Malwa dynasty and Queen Ahilyabai Holkar.",
        "To promote regional tourism, support traditional craftspeople, and celebrate Malwa's famous street food culture.",
        "Held alternately at the historic Lal Bagh Palace in Indore and the sacred riverfront of Ujjain.",
        "Features one of the most extensive food festivals in central India, celebrating Indore's reputation as the culinary capital of central India.",
        ["Nightly folk dance and music concerts featuring regional troupes from across India", "Sprawling artisan crafts bazaar with live demonstrations of Bagh block printing and Chanderi weaving", "Mega food street showcasing over 100 authentic Malwa culinary specialties"],
        "Thousands of foodies and culture lovers wander through illuminated palace grounds, relishing hot snacks and watching vibrant folk ballets.",
        ["Bhutte Ka Kees (grated corn cooked in milk with spices)", "Garadu (deep-fried spiced yam)", "Dal Bafla with Ghee", "Indori Poha with Sev", "Jaleba"],
        "Smart casuals, comfortable ethnic wear, and Chanderi cotton dupattas.",
        "Malwi folk dances: Matki dance with brass pots balanced on head, Aada-Khada, and lively folk songs.",
        "Lal Bagh Palace ornate wrought-iron gates, brass cooking cauldrons, and colorful handicraft stalls.",
        "5 Days", "Gregorian / Spring", "Held in May annually (or rotating dates in autumn).",
        "May", "ORGANIZER_ANNOUNCED", "Announced annually by MP Tourism.",
        "2026-05-08", "2027-05-07", "Madhya Pradesh Tourism Board & Indore Municipal Corporation",
        ["Madhya Pradesh"], ["Indore", "Ujjain"], ["Lal Bagh Palace Grounds Indore", "Kshipra Riverfront Ujjain"],
        "Evenings between 5:30 PM and 10:30 PM for street food tasting and cultural concerts", 2,
        "Mouthwatering gastronomic paradise, lively folk humor, exquisite royal palace surroundings, and warm Malwi hospitality.",
        "Devi Ahilyabai Holkar Airport Indore; well connected by express trains and highways.",
        "Extensive luxury and business hotels across Indore.",
        "Warm summer evenings; stay hydrated and wear light breathable cotton clothing.",
        "Patience required around popular food stalls; maintain clean eating areas using designated waste bins.",
        web="https://mptourism.com"
    ),
    F(
        "fest-nimar-utsav-maheshwar", "Nimar Utsav Maheshwar", ["Maheshwar Narmada Festival"],
        "Historical & Royal", "Holkar Dynasty Heritage & Sacred River",
        "A romantic three-day festival celebrated on the magnificent sandstone ghats of the holy Narmada River, beneath the 18th-century palace fortress of Queen Ahilyabai Holkar.",
        "Initiated by Madhya Pradesh Tourism to celebrate the glorious legacy of Rani Ahilyabai Holkar and the cultural life of the Nimar region.",
        "Celebrates the sacred Narmada River and the architectural and handloom heritage of Maheshwar.",
        "To promote cultural tourism to Maheshwar and celebrate the world-famous handwoven Maheshwari silk saree industry.",
        "Staged directly on the Ahilya Ghat steps, where towering sandstone temple carvings reflect in the calm waters of the sacred Narmada.",
        "Includes thrilling traditional boat races and swimming competitions across the Narmada River.",
        ["Deepdaan ceremony where thousands of glowing earthen lamps are released onto the Narmada at dusk", "Nightly classical dance and music concerts on the open-air Ahilya Ghat stone stage", "Exhibition and live demonstrations of handloom Maheshwari saree weaving"],
        "Connoisseurs sit on the cool stone steps as classical dancers perform beneath illuminated palace walls, with glowing lamps floating gently down the river.",
        ["Nimadi Dal Bafla", "Jowar Roti with Garlic Chutney", "Mawa Baati", "Khargone Chilies specialties", "Fresh sugarcane juice"],
        "Handloom Maheshwari silk sarees with distinctive Zari borders, dhotis, and kurtas.",
        "Classical dance dramas, soulful Nimadi folk singing (Nirguni bhajans), and flute melodies.",
        "Sandstone temple carvings of Ahilya Ghat, Narmada river currents, floating leaf lamps, and wooden handlooms.",
        "3 Days", "Hindu Lunisolar / Autumn", "Kartik Purnima (November full moon)",
        "November", "LUNISOLAR", "Celebrated around Kartik Purnima.",
        "2026-11-23", "2027-11-12", "Madhya Pradesh Tourism Board & District Administration Khargone",
        ["Madhya Pradesh"], ["Maheshwar", "Khargone"], ["Ahilya Ghat Maheshwar Fort", "Narmada Riverfront"],
        "Sunset on Kartik Purnima for the magnificent Deepdaan and evening classical concerts", 2,
        "Incomparable serene romance: magnificent royal stone fortresses glowing in warm lights, gentle river ripples, and exquisite handloom elegance.",
        "90 km south of Indore Airport (2 hours by road via Dhamnod); accessible by taxi.",
        "Heritage hotels within Ahilya Fort, riverside resorts, and boutique guesthouses in Maheshwar.",
        "Gentle stone steps down to the river; wear comfortable walking shoes.",
        "Buy authentic handwoven Maheshwari sarees directly from the Rehwa Society weaving cooperative inside the fort.",
        web="https://mptourism.com"
    ),
    F(
        "fest-orchha-mahotsav", "Orchha Mahotsav", ["Orchha Cultural Festival"],
        "Historical & Royal", "Bundela Royal Architecture & Ram Raja Heritage",
        "A captivating cultural festival celebrating the 16th-century Bundela Rajput architecture, palaces, and cenotaphs along the boulder-strewn Betwa River.",
        "Organized by Madhya Pradesh Tourism in the historic capital of the Bundela kings founded by Rudra Pratap Singh in 1501 CE.",
        "Celebrates Bundela royal chivalry, medieval architecture, and the unique tradition where Lord Rama is worshipped as the sovereign King (Ram Raja).",
        "To showcase Orchha's magnificent Jahangir Mahal, Raja Mahal, and Chaturbhuj Temple to cultural travelers.",
        "The Ram Raja Temple is the only shrine in India where Lord Rama is worshipped as a reigning monarch, receiving daily police guard of honor salutes.",
        "Features mesmerizing 3D projection mapping on palace facades, river rafting on the Betwa, and classical music recitals.",
        ["Guard of honor ceremony with police rifles at the Ram Raja Temple", "Nightly 3D projection mapping and light-and-sound show on Jahangir Mahal", "Bundeli folk dance performances and classical musical concerts in royal courtyards"],
        "Travelers explore massive ruined palace towers with panoramic views of the Betwa river, watch soaring vultures on temple spires, and attend evening concerts.",
        ["Bundelkhandi Thoke", "Dal Baati", "Kachori", "Mawa Jalebi", "Amla Candy"],
        "Traditional Bundelkhandi dhotis, colorful turbans, and elegant handloom ethnic wear.",
        "Vibrant Bundeli Rai dance, Diwari stick dance with peacock feathers, and classical vocal recitals.",
        "Multi-tiered domes of Jahangir Mahal, historic royal Chhatris (cenotaphs) along the Betwa, and Ram Raja palace.",
        "3 Days", "Gregorian / Autumn", "Held in October / November annually.",
        "October - November", "ORGANIZER_ANNOUNCED", "Announced annually by MP Tourism.",
        "2026-11-06", "2027-11-05", "Madhya Pradesh Tourism Board & Niwari District Administration",
        ["Madhya Pradesh"], ["Orchha", "Niwari"], ["Jahangir Mahal Complex", "Ram Raja Temple", "Betwa Riverbank Chhatris"],
        "Morning aarti at Ram Raja Temple and evening projection show at Jahangir Mahal", 2,
        "Enchanting medieval time-capsule where monumental stone palaces, soaring cenotaphs, and rushing river rapids transport you back 500 years.",
        "18 km from Jhansi Junction railway station; easily reached by auto-rickshaw or taxi.",
        "Heritage palace hotels (Sheesh Mahal inside the fort), riverside resorts, and boutique homestays.",
        "Uneven historic stone steps and steep palace staircases; wear comfortable flat shoes.",
        "Maintain decorum at Ram Raja Temple; leather items must be deposited outside before entering.",
        web="https://mptourism.com"
    ),
    F(
        "fest-allauddin-khan-samaroh", "Allauddin Khan Sangeet Samaroh Maihar", ["Maihar Music Festival"],
        "Art & Cultural Festival", "Indian Classical Music / Maihar Gharana",
        "A deeply reverent classical music festival celebrated at the birthplace of the world-famous Maihar Gharana founded by Baba Allauddin Khan.",
        "Initiated to honor the legendary multi-instrumentalist Baba Allauddin Khan (1862-1972), teacher of Pt. Ravi Shankar, Ustad Ali Akbar Khan, and Annapurna Devi.",
        "Celebrates the austere, disciplined traditions of the Maihar Gharana of Hindustani classical music.",
        "To preserve the unique instrumental compositions and the legendary Maihar Band created by Baba Allauddin Khan.",
        "Maihar is revered as a sacred musical pilgrimage where the master trained some of the greatest musical icons of the 20th century.",
        "Features rare live performances by the historic 'Maihar Band', an indigenous orchestra created by Baba using orphaned children after a plague in 1918.",
        ["Performance by the historic Maihar Band playing indigenous instruments (Naltarang)", "Classical instrumental recitals by leading exponents of Sitar, Sarod, and Surbahar", "Pilgrimage to the historic residence of Baba Allauddin Khan (Madina Bhavan)"],
        "Connoisseurs and disciples gather in the small pilgrim town, listening in deep silence to complex classical ragas played on sarods and sitars.",
        ["Bundelkhandi Peda", "Samosa", "Puri Sabzi", "Langar Khichdi"],
        "Simple, refined Indian attire: white khadi kurtas, dhotis, and modest sarees.",
        "Pristine Maihar Gharana instrumental classical music, Sarod solos, Sitar recitals, and orchestral band compositions.",
        "Baba Allauddin Khan's violin and sarod, Madina Bhavan courtyard, and Sharda Devi hilltop temple.",
        "3 Days", "Gregorian / Winter", "Held in February / March annually.",
        "February - March", "ORGANIZER_ANNOUNCED", "Organized annually by Ustad Allauddin Khan Sangeet Akademi.",
        "2026-02-12", "2027-02-11", "Ustad Allauddin Khan Sangeet Akademi & Satna District Administration",
        ["Madhya Pradesh"], ["Maihar", "Satna"], ["Madina Bhavan Maihar", "Town Hall Complex"],
        "Evening sessions from 6 PM to 10 PM for authentic classical instrumental recitals", 2,
        "Austere, sacred musical sanctity where modern global classical legends trace their roots back to the modest home of a saintly master.",
        "Maihar railway station is well connected on the Mumbai-Howrah line; 40 km from Satna.",
        "Guesthouses in Maihar and hotels in Satna city.",
        "Quiet, contemplative festival; audience maintains deep silence during raga alaap.",
        "Combine your visit with a climb up the 1,063 stone steps to the ancient Maa Sharda Devi Temple atop Trikuta Hill.",
        web="https://mptourism.com"
    ),
    F(
        "fest-dhrupad-samaroh-bhopal", "Dhrupad Samaroh Bhopal", ["Bhopal National Dhrupad Festival"],
        "Art & Cultural Festival", "Ancient Indian Classical Music / Dhrupad Heritage",
        "The premier national festival dedicated exclusively to Dhrupad, the oldest surviving genre of Indian classical vocal and instrumental music.",
        "Established by the Madhya Pradesh Culture Department to preserve and nurture the sublime meditative tradition of Dhrupad.",
        "Celebrates the ancient Vedic roots of Indian music, characterized by spiritual contemplation, microtonal nuances, and profound sound resonance (Naad Brahma).",
        "To provide a dedicated national platform for Dhrupad masters, disciples of the Dagar and Gwalior traditions, and new generations of practitioners.",
        "Organized in close collaboration with the renowned Dhrupad Sansthan Bhopal, the premier global academy for Dhrupad training.",
        "Features rare recitals on the ancient Rudra Veena, Surbahar, Pakhawaj, and contemplative multi-octave vocal alaap.",
        ["Meditative, unhurried solo and jugalbandi Dhrupad vocal recitals", "Rare instrumental performances on the ancient Rudra Veena and Surbahar", "Solo Pakhawaj rhythmic demonstrations exploring complex 14-beat Dhamar and 12-beat Chautal cycles"],
        "Audiences sit transfixed as deep, resonant bass notes vibrate through the hall, leading the mind into deep meditative stillness.",
        ["Bhopali Poha", "Sulemani Chai", "Mawa Baati", "Kachori"],
        "Formal ethnic attire: khadi kurtas, silk shawls, and sarees.",
        "Pure, meditative Dhrupad singing (Alaap-Jod-Jhala followed by Bandish), accompanied exclusively by Tanpura and Pakhawaj.",
        "Ancient tubular Rudra Veena with double gourd resonators, barrel-shaped wooden Pakhawaj, and glowing brass oil lamps.",
        "3 Days", "Gregorian / Autumn", "Held in November / December annually.",
        "November - December", "ORGANIZER_ANNOUNCED", "Announced annually by MP Culture Department.",
        "2026-11-13", "2027-11-12", "Ustad Allauddin Khan Sangeet Akademi & Dhrupad Sansthan",
        ["Madhya Pradesh"], ["Bhopal"], ["Ravindra Bhavan Bhopal", "Dhrupad Sansthan"],
        "Evening sessions from 6:30 PM to 10 PM for meditative listening", 2,
        "Transcendental sonic meditation: deep, primordial acoustic vibrations that quiet the modern mind and transport you to ancient Vedic hermitage roots.",
        "Easily accessible in central Bhopal via taxi, auto-rickshaw, or city bus.",
        "Hotels throughout Bhopal city.",
        "Strict meditative listening environment; audience members maintain absolute silence and avoid exiting mid-performance.",
        "Dhrupad performances involve long, gradual alaap sequences; give yourself time to settle into the meditative tempo.",
        web="https://mptourism.com"
    ),
    F(
        "fest-bhojpur-utsav", "Bhojpur Utsav", ["Bhojeshwar Temple Cultural Mahotsav"],
        "Spiritual & Temple", "Hinduism (Shaivism & Paramara Architecture)",
        "The sacred cultural festival celebrated on Maha Shivratri at the monumental 11th-century Bhojeshwar Temple, home to one of the largest Shiva Lingams in the world.",
        "Founded by the legendary polymath King Bhoja of the Paramara dynasty in the 11th century; renowned for its colossal monolithic stone architecture.",
        "Celebrates Lord Shiva and honors King Bhoja's monumental contributions to architecture, Sanskrit literature, and arts.",
        "To perform sacred Abhishek on the giant 18-foot monolithic Shiva Lingam and celebrate classical cultural heritage.",
        "The temple features an enormous polished stone lingam measuring 7.5 feet in height and 17.8 feet in circumference, set on a massive 20-foot square platform.",
        "Surrounded by ancient rock quarries with architectural blueprints incised into the stone bedrock 1,000 years ago.",
        ["Continuous Maha Abhishek of the colossal monolithic Shiva Lingam with milk and holy waters on Maha Shivratri", "Grand cultural concerts featuring classical dance and devotional music on the temple grounds", "Heritage architectural tours explaining the unique 1,000-year-old rock-cut architectural drawings"],
        "Tens of thousands of pilgrims climb the massive stone ramp, offering flowers and milk to the towering monolithic deity amidst chanting.",
        ["Prasad Laddoos", "Sabudana Vada", "Bhopali Mawa Jalebi", "Puri Sabzi"],
        "Traditional dhotis, kurtas, sarees, and modest pilgrim attire.",
        "Classical dance dramas, resonant Vedic chanting, conch blasts, and devotional bhajans.",
        "Colossal 18-foot polished stone Shiva Lingam, massive uncarved monolithic temple pillars, and Betwa river vistas.",
        "3 Days", "Hindu Lunisolar", "Culminates on Maha Shivratri (February - March)",
        "February - March", "LUNISOLAR", "Culminates on Maha Shivratri.",
        "2026-02-15", "2027-03-06", "Archaeological Survey of India & MP Culture Department",
        ["Madhya Pradesh"], ["Bhojpur", "Raisen", "Bhopal"], ["Bhojeshwar Shiva Temple Complex Bhojpur"],
        "Maha Shivratri day and evening for the grand temple illuminations and cultural concerts", 2,
        "Awe-inspiring architectural and spiritual magnitude: standing dwarfed before a colossal 1,000-year-old stone god surrounded by wild rocky countryside.",
        "28 km southeast of Bhopal; accessible by road via taxi or state transport buses.",
        "Hotels in Bhopal city; easily visited as a day trip.",
        "Massive crowds on Maha Shivratri day; follow designated queue barricades to the elevated sanctum platform.",
        "Explore the stone quarry behind the temple to see 11th-century architectural diagrams engraved directly into the bedrock.",
        web="https://mptourism.com"
    ),

    # ==================== CHHATTISGARH (8) ====================
    F(
        "fest-bastar-dussehra", "Bastar Dussehra Jagdalpur", ["World's Longest Festival"],
        "Tribal & Folk Traditions", "Indigenous Shaktism & Tribal Democracy",
        "The longest festival in the world spanning 75 continuous days, celebrated by indigenous tribes honoring Goddess Danteshwari with massive hand-built wooden chariots.",
        "Initiated in the 13th century by King Purushottam Dev of the Kakatiya dynasty after returning from a pilgrimage to Jagannath Puri with the title of 'Rath-Pati'.",
        "Unlike northern Dussehra which celebrates Rama defeating Ravana, Bastar Dussehra is dedicated entirely to Goddess Danteshwari (Mother Goddess of Bastar).",
        "To honor Goddess Danteshwari, affirm tribal council governance, and celebrate nature's bounty and tribal solidarity.",
        "Spans 75 days across 13 distinct traditional phases, entirely organized by traditional village guilds (woodcutters, rope-makers, blacksmiths, chariot-pullers).",
        "Features the pulling of colossal double-decker wooden chariots (Phul Rath and Bhitar Rath) hand-hewn by tribal carpenters without a single nail.",
        ["Pata Jatra ritual consecration of the first log of sal wood brought from the forest", "Pulling of the massive 8-wheeled double-decker wooden chariot by thousands of tribal men using thick jungle vines", "Muria Darbar where tribal village headmen (Manjhis) hold formal council with the royal Maharaja and state administrators"],
        "Over 100,000 tribal people from the deep Sal forests of Bastar camp in Jagdalpur, dancing, playing massive wooden drums, and pulling the giant chariot.",
        ["Bafauri (steamed chana dal cakes)", "Chilka Roti", "Chaprah (traditional red ant chutney)", "Mahua beverage", "Jilabi"],
        "Traditional tribal attire: white and red cotton dhotis, cowrie-shell headbands, horn headdresses, and silver ornaments.",
        "Thunderous beats of giant Mandal and Dhol drums, wailing Mohri horns, and energetic tribal Gaur and Bison-Horn Maria dances.",
        "Colossal 8-wheeled wooden chariot draped in yellow and red cloth, Goddess Danteshwari's palanquin, and thick jungle vine ropes.",
        "75 Days (Peak 10 Days)", "Hindu-Tribal Lunisolar", "Shravana Amavasya to Ashwin Shukla Trayodashi (August - October)",
        "September - October", "LUNISOLAR", "Peak rituals occur during the 10 days of Navratri leading to Vijyadashami.",
        "2026-10-11", "2027-09-30", "Bastar District Administration & Danteshwari Temple Trust",
        ["Chhattisgarh"], ["Jagdalpur", "Dantewada", "Bastar"], ["Sirhasar Chowk Jagdalpur", "Danteshwari Temple"],
        "Navratri Saptami to Vijyadashami for the chariot pulling and concluding Muria Darbar", 3,
        "Astonishing, unparalleled living anthropology: witnessing the world's longest unbroken tribal democratic festival powered by pure community muscle and faith.",
        "Jagdalpur is connected by train from Visakhapatnam and Raipur; 300 km from Raipur Airport via 4-lane highway.",
        "Hotels, tribal eco-resorts, and homestays across Jagdalpur; book well in advance for peak Dussehra days.",
        "Massive tribal crowds; stay clear of the colossal chariot wheels when the heavy ropes are pulled.",
        "Respect tribal traditions and rituals; photography is generally welcomed but ask before taking close-up portraits.",
        web="https://bastar.gov.in"
    ),
    F(
        "fest-madai-festival-bastar", "Madai Festival Bastar & Narayanpur", ["Gond Tribal Fair"],
        "Tribal & Folk Traditions", "Indigenous Gond & Maria Ancestral Deities",
        "A fascinating rotating tribal fair celebrated across the deep forest villages of Bastar, where village deity totems (Anga Dev) assemble to dance and prophesy.",
        "Ancient tribal festival observed across Bastar and Narayanpur by the Gond, Maria, Muria, and Halba communities.",
        "Celebrates the annual gathering of local deities, seasonal harvest, and community reconciliation.",
        "To appease village gods, perform sacrificial thanksgiving rites, and facilitate traditional tribal courtship.",
        "Centered around the 'Anga Dev'—sacred wooden palanquin totems representing village ancestral deities that are carried on shoulders and move in trance.",
        "The deities are believed to physically communicate through the carriers, swaying, rushing forward, and greeting neighboring gods.",
        ["Procession and dynamic greeting of sacred Anga Dev wooden totems carried by shamans", "Sacrificial offering of goats and roosters to goddess Danteshwari and local forest spirits", "Bustling tribal forest bazaar featuring brass Dhokra crafts, wrought iron, and forest herbs"],
        "Thousands of forest dwellers in tribal finery gather on village clearings, drinking Mahua, watching cockfights, and dancing late into the night.",
        ["Chaprah (red ant chutney)", "Dubki Kadi", "Millet beer (Landa)", "Mahua spirit", "Roasted meat delicacies"],
        "Vivid tribal clothing: white loincloths, heavy brass neck-rings, cowrie shell ornaments, and peacock-feather hair pins.",
        "Deep, hypnotic rhythm of Kotodoka drums, wailing bamboo horns, and circular tribal group dances.",
        "Sacred Anga Dev wooden totems draped in red cloth and peacock plumes, iron tridents, and forest clearing bonfires.",
        "3 Days (rotates across villages)", "Tribal Calendar / Winter", "Celebrated from December to March across rotating Bastar villages (flagship at Narayanpur in February).",
        "December - March", "COMMUNITY_SPECIFIC", "Rotates across villages during winter months.",
        "2026-02-23", "2027-02-12", "Narayanpur District Administration & Bastar Tribal Council",
        ["Chhattisgarh"], ["Narayanpur", "Kondagaon", "Jagdalpur", "Kanker"], ["Narayanpur Fairgrounds", "Village clearings across Bastar"],
        "Daytime from 11 AM to 5 PM when deity totems assemble and tribal dancing reaches full energy", 2,
        "Raw, unvarnished encounter with living animist spirituality, deep tribal community solidarity, and ancient forest rhythms.",
        "Narayanpur is 120 km from Jagdalpur and 240 km from Raipur; accessible by road.",
        "Simple guesthouses in Narayanpur or base yourself in Jagdalpur hotels.",
        "Remote tribal heartland; travel with a knowledgeable local guide who understands Gondi dialects.",
        "Show deep reverence for the sacred Anga Dev totems; never touch them or step in their path during trance movements.",
        web="https://narayanpur.gov.in"
    ),
    F(
        "fest-rajim-kumbh-mela", "Rajim Kumbh Mela", ["Rajim Maghi Punni Mela"],
        "Spiritual & Temple", "Hinduism (Vaishnavism / Sacred Confluence)",
        "The 'Prayag of Chhattisgarh' celebrated on the sacred Triveni Sangam where the Mahanadi, Pairi, and Sondhur rivers meet at the 8th-century Rajiv Lochan Temple.",
        "Ancient pilgrimage celebrated for over 1,200 years, centered around the 8th-century black stone temple of Lord Rajiv Lochan (Vishnu).",
        "Celebrates the holy confluence of three sacred rivers and the divine blessings of Lord Vishnu.",
        "To take the holy cleansing bath on Magh Purnima and offer prayers at the historic Kuleshwar Mahadev temple situated in the middle of the riverbed.",
        "The largest religious gathering in Chhattisgarh, bringing together lakhs of devotees, Naga sadhus, and saints of the Kabir and Satnami traditions.",
        "Features the ancient Kuleshwar Mahadev Temple built on an octagonal stone platform in the center of the riverbed, surviving centuries of monsoonal floods.",
        ["Holy cleansing dip at the Triveni Sangam on Magh Purnima dawn", "Grand Shahi Snan procession of Naga sadhus and Mahamandaleshwars", "Nightly cultural performances featuring Chhattisgarhi folk epics (Pandavani and Panthi)"],
        "Lakhs of pilgrims camp on the sandy riverbanks, bathing at sunrise, attending Satsangs, and listening to thrilling performances of the Mahabharata.",
        ["Chusela (fried rice flour bread)", "Dehrori (sweet fried rice dumplings in sugar syrup)", "Faraa (steamed rice flour rolls)", "Bafauri"],
        "Simple white dhotis, cotton kurtas, and traditional Chhattisgarhi Lugda sarees.",
        "Electric performances of Pandavani folk singing (Mahabharata balladry) with Tambura and Kartal, and energetic Panthi dance.",
        "Confluence of three sacred rivers, 8th-century carved stone temple shikharas, and floating leaf lamps.",
        "15 Days", "Hindu Lunisolar", "Magh Purnima to Maha Shivratri (February - March)",
        "February - March", "LUNISOLAR", "Begins Magh Purnima and concludes Maha Shivratri.",
        "2026-02-01", "2027-02-20", "Rajim Kumbh Mela Authority & Chhattisgarh Tourism",
        ["Chhattisgarh"], ["Rajim", "Gariaband", "Raipur"], ["Triveni Sangam Rajim", "Rajiv Lochan Temple", "Kuleshwar Mahadev Temple"],
        "Magh Purnima dawn for the sacred holy bath and evening Pandavani performances", 2,
        "Vibrant rural spirituality, breathtaking ancient temple architecture on sandy river confluences, and world-renowned folk epic storytelling.",
        "45 km south of Raipur Airport; well connected by highway buses and private cars.",
        "Hotels in Raipur city (1 hour away) or pilgrim dharamshalas in Rajim.",
        "Dusty riverbed walking; wear comfortable walking shoes and carry sun protection.",
        "Maintain deep spiritual sanctity at the river confluence; do not litter in the riverbed.",
        web="https://gariaband.nic.in"
    ),
    F(
        "fest-sirpur-dance-festival", "Sirpur National Dance and Music Festival", ["Sirpur Heritage Festival"],
        "Art & Cultural Festival", "Classical Performing Arts & Buddhist-Hindu Archaeology",
        "A magnificent three-day festival of classical music and dance staged against the red-brick 7th-century Laxman Temple and ancient Buddhist monastic ruins of Sirpur.",
        "Initiated by Chhattisgarh Tourism to highlight the extraordinary archaeological wealth of Sirpur, which was visited by Chinese traveler Xuanzang in 639 CE.",
        "Celebrates the ancient Buddhist, Hindu, and Jain syncretic civilization that flourished along the Mahanadi River.",
        "To promote archaeological conservation and present world-renowned classical performing artists in an ancient heritage setting.",
        "Staged against the exquisite red-brick Laxman Temple, one of the finest surviving 7th-century brick temples in India.",
        "Features performances by living legends of Indian classical dance and music alongside Chhattisgarhi folk artists.",
        ["Nightly classical dance and music concerts against the illuminated 7th-century red-brick temple", "Guided archaeological walks through the grand excavated Buddhist Viharas (monasteries)", "Exhibition of ancient terracotta sculptures and metal artifacts discovered at the site"],
        "Connoisseurs sit beneath cold starlit skies, enraptured as classical dancers perform intricate rhythm sequences before glowing ancient brick arches.",
        ["Chhattisgarhi Thali: Faraa, Thetthari, Khurmi", "Bafauri", "Chilka Roti", "Dal Pithi"],
        "Refined formal ethnic wear: handloom Kosa silk sarees (pride of Chhattisgarh), bandhgalas, and shawls.",
        "Classical Kathak, Odissi, Bharatanatyam, flute and sitar recitals, and traditional Chhattisgarhi Pandavani singing.",
        "Exquisite red-brick carvings of Laxman Temple, excavated stone Buddha statues, and floodlit ancient pillars.",
        "3 Days", "Gregorian / Winter", "Held in January / February annually.",
        "January - February", "ORGANIZER_ANNOUNCED", "Announced annually by Chhattisgarh Tourism.",
        "2026-01-16", "2027-01-15", "Chhattisgarh Tourism Board (CTB) & ASI",
        ["Chhattisgarh"], ["Sirpur", "Mahasamund", "Raipur"], ["Laxman Temple Complex Sirpur"],
        "Evenings between 6 PM and 9:30 PM for floodlit classical concerts and morning archaeological walks", 2,
        "Enchanting archaeological wonderland: standing among 1,400-year-old Buddhist monasteries and red-brick temples, immersed in sublime classical arts.",
        "85 km east of Raipur Airport; accessible by private taxi or tourist bus via NH-53 (1.5-hour drive).",
        "Heritage eco-resort by Chhattisgarh Tourism at Sirpur, or luxury hotels in Raipur city.",
        "Cool January evenings; carry a warm shawl or light jacket.",
        "Strict archaeological protection: no climbing or leaning against ancient fragile brick carvings.",
        web="https://chhattisgarhtourism.cg.gov.in"
    ),
    F(
        "fest-bhoramdeo-mahotsav", "Bhoramdeo Mahotsav Kawardha", ["Khajuraho of Chhattisgarh Festival"],
        "Art & Cultural Festival", "Classical Heritage & Nagara Temple Architecture",
        "A premier cultural festival staged against the 11th-century carved stone temple of Bhoramdeo, nestled in the scenic Maikal hills.",
        "Established by Chhattisgarh Tourism at the historic 11th-century temple built by King Ramchandra of the Nagavanshi dynasty.",
        "Celebrates the synthesis of medieval stone architecture, classical performing arts, and indigenous Baiga tribal culture.",
        "To showcase the 'Khajuraho of Chhattisgarh' and celebrate regional folk arts.",
        "The temple is renowned for its erotic and divine stone sculptures carved in exquisite detail on yellowish-brown sandstone.",
        "Features classical dancers and musicians performing on an open-air stage against the illuminated medieval temple spire.",
        ["Nightly classical dance and music concerts against the illuminated 11th-century temple facade", "Baiga tribal folk dance performances with rhythmic wooden stilts and drums", "Artisan crafts fair showcasing indigenous Bell Metal (Dhokra) and wrought iron crafts"],
        "Visitors admire the medieval temple carvings, watch thrilling Baiga tribal dancers leap in unison, and attend evening classical recitals.",
        ["Kawardha Peda", "Chilka Roti", "Faraa", "Dehrori", "Mahua tea"],
        "Traditional handloom Kosa silk sarees, dhotis, and ethnic Indian festive wear.",
        "Classical Indian dance forms, Baiga tribal Karma dance, and soulful Chhattisgarhi folk singing.",
        "Carved sandstone temple spire (Shikhara), erotic sculpture panels, and forested Maikal hill backdrop.",
        "3 Days", "Hindu Lunisolar / Spring", "Held during the month of March around Holi.",
        "March", "LUNISOLAR", "Held in Phalguna month around Holi.",
        "2026-03-08", "2027-03-27", "Kawardha District Administration & Chhattisgarh Tourism",
        ["Chhattisgarh"], ["Kawardha", "Kabirdham"], ["Bhoramdeo Temple Complex"],
        "Evening from 5:30 PM to 9 PM during floodlit temple concerts", 2,
        "Serene medieval architectural splendor tucked away in forested mountain foothills, filled with captivating tribal and classical rhythms.",
        "130 km northwest of Raipur Airport; accessible by road via Simga and Bemetara.",
        "Palace Kawardha heritage hotel, government guest houses, and hotels in Kawardha town (18 km away).",
        "Pleasant spring weather; comfortable walking shoes recommended for temple grounds.",
        "Strict archaeological heritage conservation rules apply; maintain respect inside the active sanctum.",
        web="https://kawardha.gov.in"
    ),
    F(
        "fest-chakradhar-samaroh", "Chakradhar Samaroh Raigarh", ["Raigarh Classical Dance & Tabla Fest"],
        "Art & Cultural Festival", "Kathak Classical Dance & Percussion Heritage",
        "The legendary 10-day classical music and dance festival commemorating Maharaja Chakradhar Singh, the royal patron of the Raigarh Gharana of Kathak.",
        "Initiated to honor Maharaja Chakradhar Singh of Raigarh (1905-1947), an accomplished dancer, percussionist, and author who established the Raigarh Gharana of Kathak.",
        "Celebrates the royal patronage of Kathak dance, intricate Tabla rhythms, and classical vocal arts.",
        "To preserve the unique syncretic aesthetic of the Raigarh Gharana, which synthesized elements of Lucknow and Jaipur Kathak with tribal rhythms.",
        "Held during Ganesh Chaturthi for 10 straight nights, drawing India's most celebrated classical dancers, vocalists, and percussionists.",
        "Known for its extraordinary audience: thousands of common citizens and connoisseurs sit together for 10 nights listening to high classical music.",
        ["Grand evening classical Kathak dance recitals by legendary exponents", "Electrifying Tabla and Pakhawaj percussion jugalbandis", "Conferment of the prestigious National Chakradhar Samman award"],
        "The festival pavilion buzzes with electric energy as audiences applaud complex rhythmic footwork (Tatkar) and lightning-fast chakkars (pirouettes).",
        ["Chhattisgarhi Kosa Peda", "Samosa with spicy chana", "Faraa", "Jalebi", "Chakradhar Tea"],
        "Formal Indian classical attire: silk kurtas, bandhgalas, and handloom Kosa silk sarees.",
        "Exquisite Raigarh Gharana Kathak dance, thunderous Tabla solos, classical Hindustani vocal, and sitar-sarod jugalbandis.",
        "Statue of Maharaja Chakradhar Singh with tabla, illuminated classical stage arches, and Kathak ankle bells (Ghungroos).",
        "10 Days", "Hindu Lunisolar", "Bhadrapada Shukla Chaturthi to Anant Chaturdashi (Ganesh Chaturthi season)",
        "August - September", "LUNISOLAR", "Runs for the 10 days of Ganeshotsav.",
        "2026-09-14", "2027-09-04", "Ustad Allauddin Khan Sangeet Akademi & Raigarh Administration",
        ["Chhattisgarh"], ["Raigarh"], ["Ramleela Maidan Raigarh"],
        "Nightly concerts from 7 PM to 11 PM during peak Kathak and Tabla performances", 3,
        "High-voltage classical ecstasy where thunderous tabla beats and virtuosic Kathak footwork captivate an audience of thousands under the open sky.",
        "Raigarh is a major railway station on the Mumbai-Howrah line; well connected by express trains.",
        "Hotels and government guest houses across Raigarh town.",
        "Massive local attendance; arrive 30 minutes before evening sessions to secure good seating.",
        "Applaud appropriately with 'Wah Wah' at the completion of complex rhythmic tihai sequences.",
        web="https://raigarh.gov.in"
    ),
    F(
        "fest-goncha-festival", "Goncha Festival Jagdalpur", ["Bastar Chariot & Tupki Carnival"],
        "Spiritual & Temple", "Tribal Vaishnavism & Bamboo Popgun War",
        "The unique tribal chariot festival celebrated alongside Jagannath Rath Yatra, famous for the playful mock war fought with bamboo popguns firing wild fruit bullets.",
        "Introduced in the 14th century by King Purushottam Dev of Bastar, integrating Jagannath temple traditions with indigenous tribal playfulness.",
        "Celebrates the chariot journey of Lord Jagannath, Balabhadra, and Subhadra through the tribal heartland.",
        "To honor Lord Jagannath and engage in the traditional friendly mock battle with 'Tupki' bamboo popguns.",
        "Completely unique to Bastar: every child and adult carries a 'Tupki' (a hollow bamboo cylinder with a piston) firing wild 'Peng' berries.",
        "Spectators and participants playfully shoot each other with harmless wild berries that pop with a loud 'thwack' sound.",
        ["Pulling of the sacred wooden chariot of Lord Jagannath by tribal devotees down Jagdalpur main avenue", "Playful mock battles with bamboo Tupki popguns firing wild Peng fruit bullets through the streets", "Ceremonial darshan and distribution of sacred Mahaprasad at the historic Jagannath Temple"],
        "Streets echo with the continuous popping sound of thousands of bamboo popguns, joyful laughter, and devotional chanting.",
        ["Bafauri", "Chilka Roti", "Jagannath Temple Khichdi Prasad", "Jalebi", "Sweet Bundi"],
        "Colorful tribal and rural attire: bright shirts, dhotis, cotton sarees, and straw hats.",
        "Lively tribal drumming, folk singing, and the loud rhythmic popping of bamboo Tupki guns.",
        "Three wooden chariots of Lord Jagannath, handcrafted bamboo Tupki popguns, and wild yellow Peng berries.",
        "1 Day", "Hindu Lunisolar", "Ashadha Shukla Dwitiya (June - July)",
        "June - July", "LUNISOLAR", "Celebrated on Ashadha Shukla Dwitiya (same day as Puri Rath Yatra).",
        "2026-07-16", "2027-07-06", "Jagannath Mandir Trust Jagdalpur & Bastar Administration",
        ["Chhattisgarh"], ["Jagdalpur", "Bastar"], ["Jagannath Temple Jagdalpur", "Main Road Jagdalpur"],
        "Afternoon between 2 PM and 6 PM during the chariot procession and Tupki games", 1,
        "Delightful, laugh-out-loud playful community joy where an entire city engages in a harmless, popping fruit mock-battle amidst deep spiritual devotion.",
        "Easily accessible in central Jagdalpur via auto-rickshaw or walking.",
        "Hotels throughout Jagdalpur city.",
        "Watch your eyes: while Peng berry bullets are small wild fruits, wear sunglasses or protective glasses on streets.",
        "Buy an authentic bamboo Tupki gun from local artisan stalls for a few rupees to join in the fun.",
        web="https://bastar.gov.in"
    ),
    F(
        "fest-raut-nacha-mahotsav", "Raut Nacha Mahotsav Bilaspur", ["Yaduvanshi Martial Dance Festival"],
        "Tribal & Folk Traditions", "Yaduvanshi Pastoral & Martial Heritage",
        "The thrilling traditional folk festival of the Yaduvanshi (cowherd) community, featuring thousands of stick-wielding warriors in mirror-work jackets.",
        "Centuries-old post-Diwali martial dance tradition commemorating Lord Krishna's victory over the tyrant King Kamsa and the martial defense of cattle.",
        "Celebrates the valor, camaraderie, and divine cattle-herding heritage of the Yaduvanshi community.",
        "To honor Lord Krishna, celebrate the bond between cowherds and cattle, and showcase traditional stick-fighting martial arts.",
        "Features the dramatic singing of 'Dohas' (rhyming couplets) by warriors who challenge competitor troupes in poetic duels.",
        "Dancers wear heavy traditional jackets covered in hundreds of tiny mirrors and cowrie shells, carrying brass bells and polished wooden sticks.",
        ["Competitive marching of hundreds of decorated Raut Nacha troupes down Bilaspur streets", "Display of synchronized stick-fighting martial choreography (Lathi Khel) and sword-defense", "Recitation of witty and heroic couplets (Dohas) praising Lord Krishna and mocking cowards"],
        "The stadium roars as wave after wave of warriors in jingling mirror jackets leap into the air, clashing their sticks in thunderous, lightning-fast rhythms.",
        ["Chhattisgarhi Faraa", "Dehrori", "Thetthari", "Chusela", "Sweet Lassi"],
        "Dazzling mirror-work jackets (Kurta), colorful turbans decorated with peacock feathers, brass waist-bells, and knee-length dhotis.",
        "Thunderous, fast-paced rhythm of Mandal drums, Sinh-Baja, and clattering wooden sticks (Lathis).",
        "Peacock-feather crests (Mor Pankh), polished wooden lathis, mirror-work jackets, and Krishna imagery.",
        "1 Day", "Hindu Lunisolar / Autumn", "Kartik Shukla Paksha (approx 10-12 days after Diwali)",
        "November", "LUNISOLAR", "Held during Kartik month following Diwali.",
        "2026-11-18", "2027-11-08", "Raut Nacha Mahotsav Samiti & Bilaspur Municipal Corporation",
        ["Chhattisgarh"], ["Bilaspur"], ["Lal Bahadur Shastri Stadium Bilaspur"],
        "Evening from 5 PM to 11 PM when competitive troupe performances take place", 1,
        "Electrifying martial spectacle: thousands of warrior dancers swirling with peacock feathers, flashing mirrors, and clattering sticks in thunderous unison.",
        "Bilaspur is a major railway headquarters on the Mumbai-Howrah mainline; 120 km from Raipur Airport.",
        "Hotels and guest houses across Bilaspur city.",
        "High crowd energy in the stadium; stay in designated spectator seating stands.",
        "Applaud the witty poetic couplets (Dohas) recited by the lead dancers.",
        web="https://bilaspur.gov.in"
    )
]
