# scripts/generator/festivals_part1.py
"""
Part 1 of VIRASAT Festival Master Database:
Jammu & Kashmir, Ladakh, Himachal Pradesh, Punjab, Chandigarh, Haryana, Delhi, Rajasthan, Gujarat, Goa, Dadra & Nagar Haveli and Daman & Diu, Maharashtra.
Total: 110 Festivals
"""

from festival_builder_helper import fest

FESTIVALS_PART1 = [
    # 1. J&K
    fest(
        "fest-tulip-festival-srinagar", "Tulip Festival Srinagar", ["Indira Gandhi Memorial Tulip Festival"],
        "Seasonal Celebrations", "Secular / Nature",
        "Asia's largest tulip festival celebrating the blooming of over 1.5 million tulips in 60 varieties against the Zabarwan range on Dal Lake.",
        "Inaugurated in 2007 by the Jammu and Kashmir Government to promote tourism in Kashmir valley prior to summer season.",
        "Inspired by Mughal garden floriculture and Himalayan spring transitions.",
        "Celebrates the arrival of spring in Kashmir after months of harsh winter chill.",
        "Symbolizes rebirth of valley life and Kashmir's centuries-old affinity with garden design.",
        "Transformed Srinagar's spring tourism economy into a premier national flower destination.",
        ["Morning walkthroughs across tiered flower beds", "Cultural handicraft stalls displaying Pashmina and walnut woodcarving", "Wazwan culinary tastings"],
        "Tourists and locals walk along colorful flower terraces overlooking Dal Lake, enjoying live Kashmiri folk music.",
        ["Kashmiri Kahwa with Saffron and Almonds", "Rogan Josh", "Dum Aloo", "Modur Pulao", "Nadru Yakhni"],
        "Traditional Pheran with Tilla embroidery and Kasaba headgear.",
        "Rouff folk dance, Chakri folk songs, and live Santoor recitals.",
        "Multi-hued blooming tulips, Dal Lake Shikaras, Chinar leaf motifs.",
        "15 to 20 days", "Gregorian / Seasonal", "Timing dependent on winter snowmelt and spring temperatures; usually starts first week of April.",
        "April", "ORGANIZER_ANNOUNCED", "Announced annually by Jammu & Kashmir Floriculture Department based on bulb bloom status.",
        "2026-04-01 to 2026-04-20", "2027-04-01 to 2027-04-20", "J&K Department of Tourism announcement",
        ["Jammu and Kashmir"], ["Srinagar"], ["Indira Gandhi Memorial Tulip Garden, Cheshmashahi"],
        "First week of April for peak flower bloom", 2,
        "Wandering through rainbow terraces of tulips, sipping hot saffron Kahwa, taking sunset shikara rides on Dal Lake.",
        "Pre-paid taxis and auto-rickshaws from Srinagar center (8 km) along Boulevard Road.",
        "Book Boulevard Road or Dal Lake houseboats weeks in advance during bloom season.",
        "High footfall on weekends; designated entry lanes and tourist security assistance booths active.",
        "Do not pluck flowers or step inside planted beds; photography allowed without tripods in crowded rows.",
        "Paved stepped terraces; wheelchair ramps available at main entrance gates.",
        "https://www.jktourism.jk.gov.in",
        ["https://www.jktourism.jk.gov.in", "https://srinagar.nic.in"]
    ),
    fest(
        "fest-kheer-bhawani-mela", "Kheer Bhawani Mela", ["Ragnya Devi Mela", "Tulmulla Festival"],
        "Religious - Hindu", "Hinduism (Kashmiri Shaivism / Shaktism)",
        "The most sacred annual pilgrimage of Kashmiri Pandits to the sacred spring shrine of Ragnya Devi at Tulmulla.",
        "Centuries-old shrine mentioned in the 12th-century Rajatarangini of Kalhana, revered by Kashmiri Hindus across generations.",
        "According to legend, Lord Rama worshiped Mata Ragnya during his exile, and Hanuman shifted the shrine to Kashmir following Rama's command.",
        "Celebrates the manifestation of Goddess Ragnya on Jyeshtha Shukla Ashtami.",
        "The spring waters inside the shrine octagonal pool naturally change color; shades of pink or milky white are considered deeply auspicious.",
        "Vital cultural bridge for Kashmiri Pandit homecoming and communal harmony with local Kashmiri Muslims offering milk and flowers.",
        ["Offering bowls of kheer (rice pudding) and milk into the sacred kund", "Chanting of Bhavani Sahasranama", "Community aarti at sunset"],
        "Thousands of devotees gather around the sacred spring, offering kheer, singing hymns, and reconnecting with ancestral roots.",
        ["Kheer (Rice Pudding)", "Nadroo Pakoda", "Kashmiri Kahwa", "Yellow Rice (Tehar)"],
        "Traditional Pheran with Taranga or white festive kurtas and sarees.",
        "Lalit chanting, Kashmiri Bhajans, and traditional conch resonance.",
        "Sacred spring kund, floating clay lamps, towering Chinar shade.",
        "1 to 2 days", "Lunisolar", "Observed on Jyeshtha Shukla Ashtami according to Kashmiri Hindu Panchang.",
        "May - June", "LUNISOLAR", "Jyeshtha Shukla Paksha Ashtami tithi.",
        "2026-06-22", "2027-06-11", "Kashmiri Pandit Sanstha Calendar",
        ["Jammu and Kashmir"], ["Tulmulla", "Ganderbal"], ["Mata Kheer Bhawani Temple Complex, Tulmulla"],
        "During Jyeshtha Ashtami day", 2,
        "Witnessing the miraculous color-changing spring, spiritual camaraderie, and authentic Kashmiri Pandit hospitality.",
        "Special security-monitored tourist buses from Srinagar (25 km via Ganderbal highway).",
        "Temple dharamshalas, Srinagar city hotels, and special government tourist camps.",
        "Heavy police and CRPF pilgrim security; orderly queue barricades around the sanctum.",
        "Strict vegetarian code within 5 km radius; leather items prohibited inside temple parikrama.",
        "Ramp access available from main gate to temple parikrama.",
        "https://ganderbal.nic.in",
        ["https://ganderbal.nic.in", "https://www.jktourism.jk.gov.in"]
    ),
    fest(
        "fest-navreh-kashmir", "Navreh (Kashmiri New Year)", ["Navreh", "Kashmiri Pandit New Year"],
        "Regional New Year Observances", "Hinduism (Kashmiri Shaivism)",
        "The auspicious lunar New Year celebrated by Kashmiri Pandits on the first day of Chaitra Navratri.",
        "Traced to the ancient Saptarshi calendar established over 5,000 years ago in the Kashmir Valley.",
        "Celebrates the descent of Goddess Sharada and the divine renewal of the cosmos at the start of spring.",
        "Marks the renewal of agriculture, scholarship, and prosperity for the coming astronomical cycle.",
        "Affirms Kashmiri identity, traditional calendar reckoning, and reverence for Goddess Sharada, patroness of learning.",
        "Recorded in medieval Sanskrit chronicles as the principal civil and spiritual festival of ancient Kashmir.",
        ["Thal Barun (filling ceremonial platter with rice, mirror, walnut, pen, currency, almanac on New Year eve)", "Viewing the Thal first thing on waking at dawn", "Offering yellow rice (Tehar) to family deity"],
        "Families wake before sunrise, view the sacred auspicious platter (Thal), prepare fragrant yellow rice (Tehar), and visit Hari Parbat (Chakreshwar).",
        ["Tehar (Turmeric scented rice)", "Dum Aloo", "Monje Gaad", "Roghni Roti"],
        "Festive new silk kurtas, pherans, and gold dejihor earrings for married women.",
        "Kashmiri devotional leelas and classical Sufiana kalam.",
        "Ceremonial Thal, Saptarshi almanac, spring almond blossoms.",
        "1 day", "Lunisolar", "Observed on Chaitra Shukla Pratipada (first day of Chaitra bright fortnight).",
        "March - April", "LUNISOLAR", "Chaitra Shukla Paksha Pratipada tithi.",
        "2026-03-20", "2027-04-07", "Kashmiri Hindu Calendar",
        ["Jammu and Kashmir", "Delhi"], ["Srinagar", "Jammu", "New Delhi"], ["Sharika Devi Temple on Hari Parbat Hill, Srinagar"],
        "Early morning sunrise on Chaitra Pratipada", 1,
        "Observing the ancient Thal Barun ritual, listening to Saptarshi calendar recitations, and climbing Hari Parbat fort.",
        "Local auto-rickshaws and taxis to Hari Parbat base.",
        "Srinagar heritage hotels, Lal Chowk, and Dal Lake area.",
        "Normal temple crowd; comfortable walking shoes required for Hari Parbat climb.",
        "Respect traditional silence during early morning Thal viewing rituals.",
        "Steep stairs at Hari Parbat; limited wheelchair accessibility at upper sanctum.",
        "https://www.jktourism.jk.gov.in",
        ["https://www.jktourism.jk.gov.in", "https://ignca.gov.in"]
    ),
    fest(
        "fest-shikara-festival-srinagar", "Srinagar Shikara Festival", ["Dal Lake Shikara Carnival"],
        "Traditional Fairs & Melas", "Cultural / Maritime",
        "Vibrant water carnival on Dal Lake celebrating the century-old cultural legacy of Kashmiri wooden boatmen.",
        "Initiated by Jammu & Kashmir Tourism to honor the iconic hand-carved wooden shikaras and their unique lifestyle.",
        "Rooted in the historical importance of Srinagar's water transport channels during the Sultanate and Dogra eras.",
        "Celebrates the craftsmanship, livelihood, and water culture of Dal Lake boatmen.",
        "Highlights sustainable lake heritage and traditional wooden boat-building arts of Rainawari.",
        "Global symbol of Kashmir's tourism hospitality and floating commerce.",
        ["Grand decorated Shikara parade", "Dragon boat style Shikara races across Dal Lake", "Floating vegetable market live exhibitions"],
        "Hundreds of shikaras decorated with colorful Kashmiri embroidery, flags, and flowers race across Dal Lake amidst cheer and folk music.",
        ["Kashmiri Wazwan dishes", "Harissa", "Seekh Tuji (Charcoal street kebabs)", "Kahwa"],
        "Embroidered tweed pherans and boatmen turbans.",
        "Live rabab and santoor players performing on floating houseboats; traditional ladishah satire.",
        "Heart-shaped carved oars, gilded shikara canopies, floating water lilies.",
        "2 to 3 days", "Seasonal", "Organized annually in July or August during peak summer lake season.",
        "July - August", "ORGANIZER_ANNOUNCED", "Announced annually by J&K Tourism Department.",
        "2026-07-25 to 2026-07-27", "2027-07-24 to 2027-07-26", "J&K Tourism Official Calendar",
        ["Jammu and Kashmir"], ["Srinagar"], ["Dal Lake, Boulevard Road, Nehru Park"],
        "Early morning and late evening during boat races", 2,
        "Riding in a competitive shikara race, floating flower shopping at dawn, hearing live Kashmiri music reverberate on water.",
        "Boulevard road taxis and direct boarding at Ghats 1 through 15.",
        "Heritage houseboats on Dal Lake and Nigeen Lake.",
        "Life jackets mandatory during all water competitions; rescue speedboats stationed across the lake.",
        "Do not throw plastic or waste into Dal Lake; treat boatmen with respect.",
        "Boarding ramps available at prominent public tourist ghats (Ghat 7 and Nehru Park jetty).",
        "https://www.jktourism.jk.gov.in",
        ["https://www.jktourism.jk.gov.in"]
    ),
    fest(
        "fest-saffron-festival-pampore", "Pampore Saffron Festival", ["Kashmir Saffron Harvest Festival"],
        "Harvest & Agricultural", "Agricultural / Cultural",
        "Celebration of the world's most precious spice during the purple saffron crocus harvest in the karewa highlands of Pampore.",
        "Pampore saffron cultivation dates back to 500 BCE, mentioned in ancient Sanskrit texts and Mughal imperial memoirs.",
        "Legend attributes the introduction of saffron bulbs to two 12th-century Sufi saints, Hazrat Khwaja Masood Wali and Hazrat Sheikh Shariffudin.",
        "Celebrates the harvest of GI-tagged Kashmiri Saffron (Kong) known for its deep crimson stigma and high crocin content.",
        "Major economic pillar supporting tens of thousands of farming households in the Pulwama district.",
        "Recognized by FAO as a Globally Important Agricultural Heritage System (GIAHS).",
        ["Plucking violet saffron flowers in the morning chill", "Manual extraction of the red stigmas (Zaffran)", "Saffron drying and grading demonstrations"],
        "Tourists walk into purple crocus fields, help local farmers pluck flowers, and purchase fresh authenticated GI-tagged saffron.",
        ["Kashmiri Saffron Kehwa", "Zafrani Phirni", "Saffron Rogan Josh", "Kashmiri Naan"],
        "Traditional woollen pherans and cotton headscarves.",
        "Kashmiri harvest folk singing and dholak beats in the fields.",
        "Purple Crocus sativus petals, crimson saffron filaments, clay drying trays.",
        "3 to 5 days", "Seasonal", "Occurs during the brief saffron flowering window from late October to early November.",
        "October - November", "SEASONAL", "Synchronized with autumnal flowering of Crocus sativus bulbs.",
        "2026-10-28 to 2026-11-01", "2027-10-27 to 2027-10-31", "Department of Agriculture & Tourism J&K",
        ["Jammu and Kashmir"], ["Pampore", "Pulwama"], ["Karewa Highlands of Pampore"],
        "Late October mornings when flowers bloom in carpets", 1,
        "Walking across fields of vivid purple flowers against blue Himalayan skies, picking saffron, and tasting pure saffron tea.",
        "Just 15 km from Srinagar along NH-44 highway; easily accessible by cab.",
        "Srinagar city hotels and local farm-stay homestays in Pampore.",
        "Field paths can be muddy; wear comfortable walking boots.",
        "Only walk on designated ridges between beds to avoid damaging tender saffron corms.",
        "Open flat agricultural fields; moderate accessibility for visitors.",
        "https://pulwama.nic.in",
        ["https://pulwama.nic.in", "https://www.jktourism.jk.gov.in"]
    )
]

print(f"Loaded Part 1 initial: {len(FESTIVALS_PART1)} festivals")
