# scripts/generator/festivals_batch1_north.py
"""
Batch 1: Northern India Festivals (J&K, Ladakh, HP, Punjab, Chandigarh, Haryana, Delhi, Rajasthan, UP, Uttarakhand)
Total: ~106 festivals
"""

from festival_builder_helper import fest

BATCH1_FESTIVALS = [
    # --- JAMMU & KASHMIR ---
    fest(
        "fest-tulip-festival-srinagar", "Tulip Festival Srinagar", ["Indira Gandhi Memorial Tulip Festival"],
        "Seasonal Celebrations", "Secular / Nature",
        "Asia's largest tulip festival celebrating the blooming of over 1.5 million tulips in 60 varieties against the Zabarwan range on Dal Lake.",
        "Inaugurated in 2007 by the Jammu and Kashmir Government to promote tourism in Kashmir valley prior to summer season.",
        "Inspired by Mughal garden floriculture and Himalayan spring transitions.",
        "Celebrates the arrival of spring in Kashmir after months of harsh winter chill.",
        "Symbolizes rebirth of valley life and Kashmir's centuries-old affinity with garden design.",
        "Transformed Srinagar's spring tourism economy into a premier national flower destination.",
        ["Morning walkthroughs across tiered flower beds", "Cultural handicraft stalls displaying Pashmina and walnut woodcarving", "Wazwan culinary tastings"],
        "Tourists and locals walk along colorful flower terraces overlooking Dal Lake, enjoying live Kashmiri folk music.",
        ["Kashmiri Kahwa with Saffron and Almonds", "Rogan Josh", "Dum Aloo", "Modur Pulao", "Nadru Yakhni"],
        "Traditional Pheran with Tilla embroidery and Kasaba headgear.",
        "Rouff folk dance, Chakri folk songs, and live Santoor recitals.",
        "Multi-hued blooming tulips, Dal Lake Shikaras, Chinar leaf motifs.",
        "15 to 20 days", "Gregorian / Seasonal", "Timing dependent on winter snowmelt and spring temperatures; usually starts first week of April.",
        "April", "ORGANIZER_ANNOUNCED", "Announced annually by Jammu & Kashmir Floriculture Department based on bulb bloom status.",
        "2026-04-01 to 2026-04-20", "2027-04-01 to 2027-04-20", "J&K Department of Tourism announcement",
        ["Jammu and Kashmir"], ["Srinagar"], ["Indira Gandhi Memorial Tulip Garden, Cheshmashahi"],
        "First week of April for peak flower bloom", 2,
        "Wandering through rainbow terraces of tulips, sipping hot saffron Kahwa, taking sunset shikara rides on Dal Lake.",
        "Pre-paid taxis and auto-rickshaws from Srinagar center (8 km) along Boulevard Road.",
        "Book Boulevard Road or Dal Lake houseboats weeks in advance during bloom season.",
        "High footfall on weekends; designated entry lanes and tourist security assistance booths active.",
        "Do not pluck flowers or step inside planted beds; photography allowed without tripods in crowded rows.",
        "Paved stepped terraces; wheelchair ramps available at main entrance gates.",
        "https://www.jktourism.jk.gov.in",
        ["https://www.jktourism.jk.gov.in", "https://srinagar.nic.in"]
    ),
    fest(
        "fest-kheer-bhawani-mela", "Kheer Bhawani Mela", ["Ragnya Devi Mela", "Tulmulla Festival"],
        "Religious - Hindu", "Hinduism (Kashmiri Shaivism / Shaktism)",
        "The most sacred annual pilgrimage of Kashmiri Pandits to the sacred spring shrine of Ragnya Devi at Tulmulla.",
        "Centuries-old shrine mentioned in the 12th-century Rajatarangini of Kalhana, revered by Kashmiri Hindus across generations.",
        "According to legend, Lord Rama worshiped Mata Ragnya during his exile, and Hanuman shifted the shrine to Kashmir following Rama's command.",
        "Celebrates the manifestation of Goddess Ragnya on Jyeshtha Shukla Ashtami.",
        "The spring waters inside the shrine octagonal pool naturally change color; shades of pink or milky white are considered deeply auspicious.",
        "Vital cultural bridge for Kashmiri Pandit homecoming and communal harmony with local Kashmiri Muslims offering milk and flowers.",
        ["Offering bowls of kheer (rice pudding) and milk into the sacred kund", "Chanting of Bhavani Sahasranama", "Community aarti at sunset"],
        "Thousands of devotees gather around the sacred spring, offering kheer, singing hymns, and reconnecting with ancestral roots.",
        ["Kheer (Rice Pudding)", "Nadroo Pakoda", "Kashmiri Kahwa", "Yellow Rice (Tehar)"],
        "Traditional Pheran with Taranga or white festive kurtas and sarees.",
        "Lalit chanting, Kashmiri Bhajans, and traditional conch resonance.",
        "Sacred spring kund, floating clay lamps, towering Chinar shade.",
        "1 to 2 days", "Lunisolar", "Observed on Jyeshtha Shukla Ashtami according to Kashmiri Hindu Panchang.",
        "May - June", "LUNISOLAR", "Jyeshtha Shukla Paksha Ashtami tithi.",
        "2026-06-22", "2027-06-11", "Kashmiri Pandit Sanstha Calendar",
        ["Jammu and Kashmir"], ["Tulmulla", "Ganderbal"], ["Mata Kheer Bhawani Temple Complex, Tulmulla"],
        "During Jyeshtha Ashtami day", 2,
        "Witnessing the miraculous color-changing spring, spiritual camaraderie, and authentic Kashmiri Pandit hospitality.",
        "Special security-monitored tourist buses from Srinagar (25 km via Ganderbal highway).",
        "Temple dharamshalas, Srinagar city hotels, and special government tourist camps.",
        "Heavy police and CRPF pilgrim security; orderly queue barricades around the sanctum.",
        "Strict vegetarian code within 5 km radius; leather items prohibited inside temple parikrama.",
        "Ramp access available from main gate to temple parikrama.",
        "https://ganderbal.nic.in",
        ["https://ganderbal.nic.in", "https://www.jktourism.jk.gov.in"]
    ),
    fest(
        "fest-navreh-kashmir", "Navreh (Kashmiri New Year)", ["Navreh", "Kashmiri Pandit New Year"],
        "Regional New Year Observances", "Hinduism (Kashmiri Shaivism)",
        "The auspicious lunar New Year celebrated by Kashmiri Pandits on the first day of Chaitra Navratri.",
        "Traced to the ancient Saptarshi calendar established over 5,000 years ago in the Kashmir Valley.",
        "Celebrates the descent of Goddess Sharada and the divine renewal of the cosmos at the start of spring.",
        "Marks the renewal of agriculture, scholarship, and prosperity for the coming astronomical cycle.",
        "Affirms Kashmiri identity, traditional calendar reckoning, and reverence for Goddess Sharada, patroness of learning.",
        "Recorded in medieval Sanskrit chronicles as the principal civil and spiritual festival of ancient Kashmir.",
        ["Thal Barun (filling ceremonial platter with rice, mirror, walnut, pen, currency, almanac on New Year eve)", "Viewing the Thal first thing on waking at dawn", "Offering yellow rice (Tehar) to family deity"],
        "Families wake before sunrise, view the sacred auspicious platter (Thal), prepare fragrant yellow rice (Tehar), and visit Hari Parbat (Chakreshwar).",
        ["Tehar (Turmeric scented rice)", "Dum Aloo", "Monje Gaad", "Roghni Roti"],
        "Festive new silk kurtas, pherans, and gold dejihor earrings for married women.",
        "Kashmiri devotional leelas and classical Sufiana kalam.",
        "Ceremonial Thal, Saptarshi almanac, spring almond blossoms.",
        "1 day", "Lunisolar", "Observed on Chaitra Shukla Pratipada (first day of Chaitra bright fortnight).",
        "March - April", "LUNISOLAR", "Chaitra Shukla Paksha Pratipada tithi.",
        "2026-03-20", "2027-04-07", "Kashmiri Hindu Calendar",
        ["Jammu and Kashmir", "Delhi"], ["Srinagar", "Jammu", "New Delhi"], ["Sharika Devi Temple on Hari Parbat Hill, Srinagar"],
        "Early morning sunrise on Chaitra Pratipada", 1,
        "Observing the ancient Thal Barun ritual, listening to Saptarshi calendar recitations, and climbing Hari Parbat fort.",
        "Local auto-rickshaws and taxis to Hari Parbat base.",
        "Srinagar heritage hotels, Lal Chowk, and Dal Lake area.",
        "Normal temple crowd; comfortable walking shoes required for Hari Parbat climb.",
        "Respect traditional silence during early morning Thal viewing rituals.",
        "Steep stairs at Hari Parbat; limited wheelchair accessibility at upper sanctum.",
        "https://www.jktourism.jk.gov.in",
        ["https://www.jktourism.jk.gov.in", "https://ignca.gov.in"]
    ),
    fest(
        "fest-shikara-festival-srinagar", "Srinagar Shikara Festival", ["Dal Lake Shikara Carnival"],
        "Traditional Fairs & Melas", "Cultural / Maritime",
        "Vibrant water carnival on Dal Lake celebrating the century-old cultural legacy of Kashmiri wooden boatmen.",
        "Initiated by Jammu & Kashmir Tourism to honor the iconic hand-carved wooden shikaras and their unique lifestyle.",
        "Rooted in the historical importance of Srinagar's water transport channels during the Sultanate and Dogra eras.",
        "Celebrates the craftsmanship, livelihood, and water culture of Dal Lake boatmen.",
        "Highlights sustainable lake heritage and traditional wooden boat-building arts of Rainawari.",
        "Global symbol of Kashmir's tourism hospitality and floating commerce.",
        ["Grand decorated Shikara parade", "Dragon boat style Shikara races across Dal Lake", "Floating vegetable market live exhibitions"],
        "Hundreds of shikaras decorated with colorful Kashmiri embroidery, flags, and flowers race across Dal Lake amidst cheer and folk music.",
        ["Kashmiri Wazwan dishes", "Harissa", "Seekh Tuji (Charcoal street kebabs)", "Kahwa"],
        "Embroidered tweed pherans and boatmen turbans.",
        "Live rabab and santoor players performing on floating houseboats; traditional ladishah satire.",
        "Heart-shaped carved oars, gilded shikara canopies, floating water lilies.",
        "2 to 3 days", "Seasonal", "Organized annually in July or August during peak summer lake season.",
        "July - August", "ORGANIZER_ANNOUNCED", "Announced annually by J&K Tourism Department.",
        "2026-07-25 to 2026-07-27", "2027-07-24 to 2027-07-26", "J&K Tourism Official Calendar",
        ["Jammu and Kashmir"], ["Srinagar"], ["Dal Lake, Boulevard Road, Nehru Park"],
        "Early morning and late evening during boat races", 2,
        "Riding in a competitive shikara race, floating flower shopping at dawn, hearing live Kashmiri music reverberate on water.",
        "Boulevard road taxis and direct boarding at Ghats 1 through 15.",
        "Heritage houseboats on Dal Lake and Nigeen Lake.",
        "Life jackets mandatory during all water competitions; rescue speedboats stationed across the lake.",
        "Do not throw plastic or waste into Dal Lake; treat boatmen with respect.",
        "Boarding ramps available at prominent public tourist ghats (Ghat 7 and Nehru Park jetty).",
        "https://www.jktourism.jk.gov.in",
        ["https://www.jktourism.jk.gov.in"]
    ),
    fest(
        "fest-saffron-festival-pampore", "Pampore Saffron Festival", ["Kashmir Saffron Harvest Festival"],
        "Harvest & Agricultural", "Agricultural / Cultural",
        "Celebration of the world's most precious spice during the purple saffron crocus harvest in the karewa highlands of Pampore.",
        "Pampore saffron cultivation dates back to 500 BCE, mentioned in ancient Sanskrit texts and Mughal imperial memoirs.",
        "Legend attributes the introduction of saffron bulbs to two 12th-century Sufi saints, Hazrat Khwaja Masood Wali and Hazrat Sheikh Shariffudin.",
        "Celebrates the harvest of GI-tagged Kashmiri Saffron (Kong) known for its deep crimson stigma and high crocin content.",
        "Major economic pillar supporting tens of thousands of farming households in the Pulwama district.",
        "Recognized by FAO as a Globally Important Agricultural Heritage System (GIAHS).",
        ["Plucking violet saffron flowers in the morning chill", "Manual extraction of the red stigmas (Zaffran)", "Saffron drying and grading demonstrations"],
        "Tourists walk into purple crocus fields, help local farmers pluck flowers, and purchase fresh authenticated GI-tagged saffron.",
        ["Kashmiri Saffron Kehwa", "Zafrani Phirni", "Saffron Rogan Josh", "Kashmiri Naan"],
        "Traditional woollen pherans and cotton headscarves.",
        "Kashmiri harvest folk singing and dholak beats in the fields.",
        "Purple Crocus sativus petals, crimson saffron filaments, clay drying trays.",
        "3 to 5 days", "Seasonal", "Occurs during the brief saffron flowering window from late October to early November.",
        "October - November", "SEASONAL", "Synchronized with autumnal flowering of Crocus sativus bulbs.",
        "2026-10-28 to 2026-11-01", "2027-10-27 to 2027-10-31", "Department of Agriculture & Tourism J&K",
        ["Jammu and Kashmir"], ["Pampore", "Pulwama"], ["Karewa Highlands of Pampore"],
        "Late October mornings when flowers bloom in carpets", 1,
        "Walking across fields of vivid purple flowers against blue Himalayan skies, picking saffron, and tasting pure saffron tea.",
        "Just 15 km from Srinagar along NH-44 highway; easily accessible by cab.",
        "Srinagar city hotels and local farm-stay homestays in Pampore.",
        "Field paths can be muddy; wear comfortable walking boots.",
        "Only walk on designated ridges between beds to avoid damaging tender saffron corms.",
        "Open flat agricultural fields; moderate accessibility for visitors.",
        "https://pulwama.nic.in",
        ["https://pulwama.nic.in", "https://www.jktourism.jk.gov.in"]
    ),
    fest(
        "fest-gurez-festival", "Gurez Valley Festival", ["Dard-Shin Cultural Festival"],
        "Tribal & Indigenous Celebrations", "Tribal / Dardic Culture",
        "Cultural festival celebrating the unique Dard-Shin tribal heritage and virgin natural scenery of the remote Gurez Valley along the Kishanganga River.",
        "Gurez was an ancient corridor on the Silk Route connecting Kashmir with Gilgit and Central Asia, inhabited by the Dardic Shina-speaking people.",
        "Celebrates the legendary love story of Kashmiri poetess-queen Habba Khatoon and Emperor Yousuf Shah Chak near Habba Khatoon peak.",
        "Promotes border tourism, preserving Dardic folk language, crafts, and centuries-old wooden log houses.",
        "Crucial initiative for cultural preservation of the vulnerable Dard-Shin indigenous community.",
        "Strategic and historical crossroads on the ancient trans-Himalayan trade routes.",
        ["Dardic Shina folk song recitals", "Archery and traditional equestrian games", "White-water rafting on Kishanganga River"],
        "Tribal elders and youth perform historic Dardic sword and scarf dances, display wooden artefacts, and guide eco-treks.",
        ["Gurezi Trout Fish Curry", "Buckwheat pancakes (Kuttu)", "Wild Morel Mushroom Pulao", "Salted Butter Tea (Noon Chai)"],
        "Traditional heavy woolen robes, woven waistbands, and Dardic round caps adorned with juniper sprigs.",
        "Shina tribal folk songs, flute melodies, and energetic dholak dances.",
        "Habba Khatoon peak, carved log houses, juniper incense.",
        "2 to 3 days", "Seasonal", "Organized in mid-summer (July/August) when Razdan Pass is snow-free.",
        "July - August", "ORGANIZER_ANNOUNCED", "Announced by Bandipora District Administration and J&K Tourism.",
        "2026-08-05 to 2026-08-07", "2027-08-04 to 2027-08-06", "Bandipora District Official Portal",
        ["Jammu and Kashmir"], ["Dawar", "Gurez"], ["Dawar Ground, Gurez Valley"],
        "July to August during warm sunny mountain weather", 3,
        "Gazing at the pyramid-shaped Habba Khatoon peak, river rafting on the Kishanganga, and experiencing untouched Dardic tribal culture.",
        "6-hour mountain drive from Srinagar (125 km) via Bandipora and the high Razdan Pass (11,672 ft).",
        "Government tourist rest houses, J&K Tourism log huts, and village eco-homestays in Dawar.",
        "Border area; Indian tourists require government photo ID at check-posts; foreign tourists require permits.",
        "Respect the cultural modesty of remote villagers; ask permission before photographing tribal elders.",
        "Remote mountain valley; limited accessibility for wheelchairs.",
        "https://bandipora.nic.in",
        ["https://bandipora.nic.in", "https://www.jktourism.jk.gov.in"]
    ),
    fest(
        "fest-baisakhi-mughal-gardens", "Baisakhi at Mughal Gardens Srinagar", ["Kashmir Baisakhi Mela"],
        "Harvest & Agricultural", "Hinduism / Sikhism / Cultural",
        "Spring harvest celebration observed amidst blooming terraced fountains of Shalimar and Nishat Gardens.",
        "Dating back to the Mughal era when Jahangir and Shah Jahan laid out pleasure gardens that bloomed during Baisakhi.",
        "Celebrates the ripening of the rabi crop and the formal opening of tourist season in the Kashmir valley.",
        "Celebrates nature's abundance, water channels, and multi-faith joy in Kashmir.",
        "Living showcase of Mughal water engineering and Kashmir's secular cultural syncretism.",
        ["Community picnics under Chinar trees", "Special illumination of Mughal water cascades", "Family gatherings in Shalimar Bagh"],
        "Families lay out carpets on garden terraces, brew Kahwa on portable samovars, and celebrate spring.",
        ["Nadroo Yakhni", "Kashmiri Pulao", "Phirni", "Kulcha with Pink Tea"],
        "Brightly colored festive salwar kameez and pherans.",
        "Live Santoor, Kashmiri folk music, and children performing swings.",
        "Mughal water cascades, ancient Chinar leaves, spring flower beds.",
        "1 day", "Solar", "Celebrated on the first day of the solar month of Vaisakh (April 13 or 14).",
        "April", "SOLAR", "Mesha Sankranti solar transition.",
        "2026-04-14", "2027-04-14", "Official Solar Almanac",
        ["Jammu and Kashmir"], ["Srinagar"], ["Shalimar Bagh, Nishat Bagh, Chashme Shahi"],
        "Afternoon and evening on April 13/14", 1,
        "Lounging on lush Mughal garden lawns with water fountains sparkling, surrounded by snowy mountain peaks.",
        "Boulevard road city buses, taxis, and shikara connections.",
        "Srinagar city hotels and Dal Lake houseboats.",
        "High family footfall; orderly ticket counter queues.",
        "Do not step into historic fountains or litter garden lawns.",
        "Terraced gardens require climbing steps; lower terraces are wheelchair accessible.",
        "https://www.jktourism.jk.gov.in",
        ["https://www.jktourism.jk.gov.in"]
    ),
    fest(
        "fest-urs-shah-e-hamdan", "Urs Shah-e-Hamdan Srinagar", ["Urs Mir Sayyid Ali Hamadani"],
        "Religious - Islamic", "Islam (Sufism)",
        "The revered annual Urs of Mir Sayyid Ali Hamadani, the 14th-century Persian Sufi saint who introduced Islam and Persian arts to Kashmir.",
        "Mir Sayyid Ali Hamadani (popularly Shah-e-Hamdan) arrived in Kashmir from Hamadan, Iran, with 700 craft masters, introducing carpet weaving, pashmina, and papier-mâché.",
        "Celebrates the saint's passing (Wafat) and honors his monumental spiritual and economic contribution to Kashmir.",
        "Deep spiritual reverence across Kashmir; marks the origin of Kashmir's artisan guild traditions.",
        "Foundational cultural event in the history of Kashmiri Islam and world-renowned handicraft industries.",
        ["Recitation of Awrad-e-Fathiyya prayers", "Special congregational namaz along Jhelum riverbank", "Display of holy relics"],
        "Tens of thousands of devotees congregate at Khanqah-e-Moula on the banks of the Jhelum river, offering prayers and eating blessed halwa.",
        ["Nadir Monji", "Halwa Paratha", "Kashmiri Noon Chai", "Bakarkhani"],
        "Traditional white kurta-pyjama, skullcaps, and embroidered pherans.",
        "Spiritual Sufiana recitations, Naat, and rhythmic group dhikr.",
        "Timber pagoda spire of Khanqah, papier-mâché painted ceiling, green flags.",
        "1 to 2 days", "Lunar", "Observed on the 6th day of the Islamic lunar month of Dhu al-Hijjah.",
        "Variable (Lunar)", "LUNAR", "6th of Dhu al-Hijjah in Islamic Hijri calendar.",
        "2026-05-23", "2027-05-12", "Islamic Hijri Calendar / J&K Waqf Board",
        ["Jammu and Kashmir"], ["Srinagar"], ["Khanqah-e-Moula, Old City Srinagar"],
        "During congregational prayers on 6th Dhu al-Hijjah", 1,
        "Admiring the 1395 CE all-wood architecture of Khanqah-e-Moula without nails, soaking in profound Sufi devotion along the river Jhelum.",
        "Located in downtown Srinagar (Zaina Kadal); auto-rickshaw or walking through old city bazaars.",
        "Srinagar city hotels; limited tourist stays in downtown.",
        "Dense crowds around the shrine; modesty and patience essential.",
        "Remove footwear before entering timber shrine; head covering mandatory for all visitors.",
        "Ground floor accessible; narrow doorways inside historic shrine.",
        "https://srinagar.nic.in",
        ["https://srinagar.nic.in", "https://www.jktourism.jk.gov.in"]
    )
]

print(f"Loaded Batch 1 base: {len(BATCH1_FESTIVALS)} festivals")
