# scripts/generator/festivals_north.py
"""
Festivals of Northern India:
Jammu & Kashmir, Ladakh, Himachal Pradesh, Punjab, Chandigarh, Haryana, Delhi, Rajasthan, Uttar Pradesh, Uttarakhand.
"""

from festival_builder_helper import fest

FESTIVALS_NORTH = [
    # --- JAMMU & KASHMIR ---
    fest(
        "fest-tulip-festival-srinagar", "Tulip Festival Srinagar", ["Indira Gandhi Memorial Tulip Festival"],
        "Seasonal Celebrations", "Secular / Nature",
        "Asia's largest tulip festival celebrating the blooming of over 1.5 million tulips in 60 varieties against the Zabarwan range on Dal Lake.",
        "Inaugurated in 2007 by the Jammu and Kashmir Government to promote tourism in Kashmir valley prior to summer season.",
        "Inspired by Mughal garden floriculture and Himalayan spring transitions.",
        "Celebrates the arrival of spring in Kashmir after months of harsh winter chill.",
        "Symbolizes rebirth of valley life and Kashmir's centuries-old affinity with garden design.",
        "Transformed Srinagar's spring tourism economy into a premier national flower destination.",
        ["Morning walkthroughs across tiered flower beds", "Cultural handicraft stalls displaying Pashmina and walnut woodcarving", "Wazwan culinary tastings"],
        "Tourists and locals walk along colorful flower terraces overlooking Dal Lake, enjoying live Kashmiri folk music.",
        ["Kashmiri Kahwa with Saffron and Almonds", "Rogan Josh", "Dum Aloo", "Modur Pulao", "Nadru Yakhni"],
        "Traditional Pheran with Tilla embroidery and Kasaba headgear.",
        "Rouff folk dance, Chakri folk songs, and live Santoor recitals.",
        "Multi-hued blooming tulips, Dal Lake Shikaras, Chinar leaf motifs.",
        "15 to 20 days", "Gregorian / Seasonal", "Timing dependent on winter snowmelt and spring temperatures; usually starts first week of April.",
        "April", "ORGANIZER_ANNOUNCED", "Announced annually by Jammu & Kashmir Floriculture Department based on bulb bloom status.",
        "2026-04-01 to 2026-04-20", "2027-04-01 to 2027-04-20", "J&K Department of Tourism announcement",
        ["Jammu and Kashmir"], ["Srinagar"], ["Indira Gandhi Memorial Tulip Garden, Cheshmashahi"],
        "First week of April for peak flower bloom", 2,
        "Wandering through rainbow terraces of tulips, sipping hot saffron Kahwa, taking sunset shikara rides on Dal Lake.",
        "Pre-paid taxis and auto-rickshaws from Srinagar center (8 km) along Boulevard Road.",
        "Book Boulevard Road or Dal Lake houseboats weeks in advance during bloom season.",
        "High footfall on weekends; designated entry lanes and tourist security assistance booths active.",
        "Do not pluck flowers or step inside planted beds; photography allowed without tripods in crowded rows.",
        "Paved stepped terraces; wheelchair ramps available at main entrance gates.",
        "https://www.jktourism.jk.gov.in",
        ["https://www.jktourism.jk.gov.in", "https://srinagar.nic.in"]
    ),
    fest(
        "fest-kheer-bhawani-mela", "Kheer Bhawani Mela", ["Ragnya Devi Mela", "Tulmulla Festival"],
        "Religious - Hindu", "Hinduism (Kashmiri Shaivism / Shaktism)",
        "The most sacred annual pilgrimage of Kashmiri Pandits to the sacred spring shrine of Ragnya Devi at Tulmulla.",
        "Centuries-old shrine mentioned in the 12th-century Rajatarangini of Kalhana, revered by Kashmiri Hindus across generations.",
        "According to legend, Lord Rama worshiped Mata Ragnya during his exile, and Hanuman shifted the shrine to Kashmir following Rama's command.",
        "Celebrates the manifestation of Goddess Ragnya on Jyeshtha Shukla Ashtami.",
        "The spring waters inside the shrine octagonal pool naturally change color; shades of pink or milky white are considered deeply auspicious.",
        "Vital cultural bridge for Kashmiri Pandit homecoming and communal harmony with local Kashmiri Muslims offering milk and flowers.",
        ["Offering bowls of kheer (rice pudding) and milk into the sacred kund", "Chanting of Bhavani Sahasranama", "Community aarti at sunset"],
        "Thousands of devotees gather around the sacred spring, offering kheer, singing hymns, and reconnecting with ancestral roots.",
        ["Kheer (Rice Pudding)", "Nadroo Pakoda", "Kashmiri Kahwa", "Yellow Rice (Tehar)"],
        "Traditional Pheran with Taranga or white festive kurtas and sarees.",
        "Lalit chanting, Kashmiri Bhajans, and traditional conch resonance.",
        "Sacred spring kund, floating clay lamps, towering Chinar shade.",
        "1 to 2 days", "Lunisolar", "Observed on Jyeshtha Shukla Ashtami according to Kashmiri Hindu Panchang.",
        "May - June", "LUNISOLAR", "Jyeshtha Shukla Paksha Ashtami tithi.",
        "2026-06-22", "2027-06-11", "Kashmiri Pandit Sanstha Calendar",
        ["Jammu and Kashmir"], ["Tulmulla", "Ganderbal"], ["Mata Kheer Bhawani Temple Complex, Tulmulla"],
        "During Jyeshtha Ashtami day", 2,
        "Witnessing the miraculous color-changing spring, spiritual camaraderie, and authentic Kashmiri Pandit hospitality.",
        "Special security-monitored tourist buses from Srinagar (25 km via Ganderbal highway).",
        "Temple dharamshalas, Srinagar city hotels, and special government tourist camps.",
        "Heavy police and CRPF pilgrim security; orderly queue barricades around the sanctum.",
        "Strict vegetarian code within 5 km radius; leather items prohibited inside temple parikrama.",
        "Ramp access available from main gate to temple parikrama.",
        "https://ganderbal.nic.in",
        ["https://ganderbal.nic.in", "https://www.jktourism.jk.gov.in"]
    ),
    fest(
        "fest-navreh-kashmir", "Navreh (Kashmiri New Year)", ["Navreh", "Kashmiri Pandit New Year"],
        "Regional New Year Observances", "Hinduism (Kashmiri Shaivism)",
        "The auspicious lunar New Year celebrated by Kashmiri Pandits on the first day of Chaitra Navratri.",
        "Traced to the ancient Saptarshi calendar established over 5,000 years ago in the Kashmir Valley.",
        "Celebrates the descent of Goddess Sharada and the divine renewal of the cosmos at the start of spring.",
        "Marks the renewal of agriculture, scholarship, and prosperity for the coming astronomical cycle.",
        "Affirms Kashmiri identity, traditional calendar reckoning, and reverence for Goddess Sharada, patroness of learning.",
        "Recorded in medieval Sanskrit chronicles as the principal civil and spiritual festival of ancient Kashmir.",
        ["Thal Barun (filling ceremonial platter with rice, mirror, walnut, pen, currency, almanac on New Year eve)", "Viewing the Thal first thing on waking at dawn", "Offering yellow rice (Tehar) to family deity"],
        "Families wake before sunrise, view the sacred auspicious platter (Thal), prepare fragrant yellow rice (Tehar), and visit Hari Parbat (Chakreshwar).",
        ["Tehar (Turmeric scented rice)", "Dum Aloo", "Monje Gaad", "Roghni Roti"],
        "Festive new silk kurtas, pherans, and gold dejihor earrings for married women.",
        "Kashmiri devotional leelas and classical Sufiana kalam.",
        "Ceremonial Thal, Saptarshi almanac, spring almond blossoms.",
        "1 day", "Lunisolar", "Observed on Chaitra Shukla Pratipada (first day of Chaitra bright fortnight).",
        "March - April", "LUNISOLAR", "Chaitra Shukla Paksha Pratipada tithi.",
        "2026-03-20", "2027-04-07", "Kashmiri Hindu Calendar",
        ["Jammu and Kashmir", "Delhi"], ["Srinagar", "Jammu", "New Delhi"], ["Sharika Devi Temple on Hari Parbat Hill, Srinagar"],
        "Early morning sunrise on Chaitra Pratipada", 1,
        "Observing the ancient Thal Barun ritual, listening to Saptarshi calendar recitations, and climbing Hari Parbat fort.",
        "Local auto-rickshaws and taxis to Hari Parbat base.",
        "Srinagar heritage hotels, Lal Chowk, and Dal Lake area.",
        "Normal temple crowd; comfortable walking shoes required for Hari Parbat climb.",
        "Respect traditional silence during early morning Thal viewing rituals.",
        "Steep stairs at Hari Parbat; limited wheelchair accessibility at upper sanctum.",
        "https://www.jktourism.jk.gov.in",
        ["https://www.jktourism.jk.gov.in", "https://ignca.gov.in"]
    ),
    fest(
        "fest-shikara-festival-srinagar", "Srinagar Shikara Festival", ["Dal Lake Shikara Carnival"],
        "Traditional Fairs & Melas", "Cultural / Maritime",
        "Vibrant water carnival on Dal Lake celebrating the century-old cultural legacy of Kashmiri wooden boatmen.",
        "Initiated by Jammu & Kashmir Tourism to honor the iconic hand-carved wooden shikaras and their unique lifestyle.",
        "Rooted in the historical importance of Srinagar's water transport channels during the Sultanate and Dogra eras.",
        "Celebrates the craftsmanship, livelihood, and water culture of Dal Lake boatmen.",
        "Highlights sustainable lake heritage and traditional wooden boat-building arts of Rainawari.",
        "Global symbol of Kashmir's tourism hospitality and floating commerce.",
        ["Grand decorated Shikara parade", "Dragon boat style Shikara races across Dal Lake", "Floating vegetable market live exhibitions"],
        "Hundreds of shikaras decorated with colorful Kashmiri embroidery, flags, and flowers race across Dal Lake amidst cheer and folk music.",
        ["Kashmiri Wazwan dishes", "Harissa", "Seekh Tuji (Charcoal street kebabs)", "Kahwa"],
        "Embroidered tweed pherans and boatmen turbans.",
        "Live rabab and santoor players performing on floating houseboats; traditional ladishah satire.",
        "Heart-shaped carved oars, gilded shikara canopies, floating water lilies.",
        "2 to 3 days", "Seasonal", "Organized annually in July or August during peak summer lake season.",
        "July - August", "ORGANIZER_ANNOUNCED", "Announced annually by J&K Tourism Department.",
        "2026-07-25 to 2026-07-27", "2027-07-24 to 2027-07-26", "J&K Tourism Official Calendar",
        ["Jammu and Kashmir"], ["Srinagar"], ["Dal Lake, Boulevard Road, Nehru Park"],
        "Early morning and late evening during boat races", 2,
        "Riding in a competitive shikara race, floating flower shopping at dawn, hearing live Kashmiri music reverberate on water.",
        "Boulevard road taxis and direct boarding at Ghats 1 through 15.",
        "Heritage houseboats on Dal Lake and Nigeen Lake.",
        "Life jackets mandatory during all water competitions; rescue speedboats stationed across the lake.",
        "Do not throw plastic or waste into Dal Lake; treat boatmen with respect.",
        "Boarding ramps available at prominent public tourist ghats (Ghat 7 and Nehru Park jetty).",
        "https://www.jktourism.jk.gov.in",
        ["https://www.jktourism.jk.gov.in"]
    ),
    fest(
        "fest-saffron-festival-pampore", "Pampore Saffron Festival", ["Kashmir Saffron Harvest Festival"],
        "Harvest & Agricultural", "Agricultural / Cultural",
        "Celebration of the world's most precious spice during the purple saffron crocus harvest in the karewa highlands of Pampore.",
        "Pampore saffron cultivation dates back to 500 BCE, mentioned in ancient Sanskrit texts and Mughal imperial memoirs.",
        "Legend attributes the introduction of saffron bulbs to two 12th-century Sufi saints, Hazrat Khwaja Masood Wali and Hazrat Sheikh Shariffudin.",
        "Celebrates the harvest of GI-tagged Kashmiri Saffron (Kong) known for its deep crimson stigma and high crocin content.",
        "Major economic pillar supporting tens of thousands of farming households in the Pulwama district.",
        "Recognized by FAO as a Globally Important Agricultural Heritage System (GIAHS).",
        ["Plucking violet saffron flowers in the morning chill", "Manual extraction of the red stigmas (Zaffran)", "Saffron drying and grading demonstrations"],
        "Tourists walk into purple crocus fields, help local farmers pluck flowers, and purchase fresh authenticated GI-tagged saffron.",
        ["Kashmiri Saffron Kehwa", "Zafrani Phirni", "Saffron Rogan Josh", "Kashmiri Naan"],
        "Traditional woollen pherans and cotton headscarves.",
        "Kashmiri harvest folk singing and dholak beats in the fields.",
        "Purple Crocus sativus petals, crimson saffron filaments, clay drying trays.",
        "3 to 5 days", "Seasonal", "Occurs during the brief saffron flowering window from late October to early November.",
        "October - November", "SEASONAL", "Synchronized with autumnal flowering of Crocus sativus bulbs.",
        "2026-10-28 to 2026-11-01", "2027-10-27 to 2027-10-31", "Department of Agriculture & Tourism J&K",
        ["Jammu and Kashmir"], ["Pampore", "Pulwama"], ["Karewa Highlands of Pampore"],
        "Late October mornings when flowers bloom in carpets", 1,
        "Walking across fields of vivid purple flowers against blue Himalayan skies, picking saffron, and tasting pure saffron tea.",
        "Just 15 km from Srinagar along NH-44 highway; easily accessible by cab.",
        "Srinagar city hotels and local farm-stay homestays in Pampore.",
        "Field paths can be muddy; wear comfortable walking boots.",
        "Only walk on designated ridges between beds to avoid damaging tender saffron corms.",
        "Open flat agricultural fields; moderate accessibility for visitors.",
        "https://pulwama.nic.in",
        ["https://pulwama.nic.in", "https://www.jktourism.jk.gov.in"]
    ),
    fest(
        "fest-gurez-festival", "Gurez Valley Festival", ["Dard-Shin Cultural Festival"],
        "Tribal & Indigenous Celebrations", "Tribal / Dardic Culture",
        "Cultural festival celebrating the unique Dard-Shin tribal heritage and virgin natural scenery of the remote Gurez Valley along the Kishanganga River.",
        "Gurez was an ancient corridor on the Silk Route connecting Kashmir with Gilgit and Central Asia, inhabited by the Dardic Shina-speaking people.",
        "Celebrates the legendary love story of Kashmiri poetess-queen Habba Khatoon and Emperor Yousuf Shah Chak near Habba Khatoon peak.",
        "Promotes border tourism, preserving Dardic folk language, crafts, and centuries-old wooden log houses.",
        "Crucial initiative for cultural preservation of the vulnerable Dard-Shin indigenous community.",
        "Strategic and historical crossroads on the ancient trans-Himalayan trade routes.",
        ["Dardic Shina folk song recitals", "Archery and traditional equestrian games", "White-water rafting on Kishanganga River"],
        "Tribal elders and youth perform historic Dardic sword and scarf dances, display wooden artefacts, and guide eco-treks.",
        ["Gurezi Trout Fish Curry", "Buckwheat pancakes (Kuttu)", "Wild Morel Mushroom Pulao", "Salted Butter Tea (Noon Chai)"],
        "Traditional heavy woolen robes, woven waistbands, and Dardic round caps adorned with juniper sprigs.",
        "Shina tribal folk songs, flute melodies, and energetic dholak dances.",
        "Habba Khatoon peak, carved log houses, juniper incense.",
        "2 to 3 days", "Seasonal", "Organized in mid-summer (July/August) when Razdan Pass is snow-free.",
        "July - August", "ORGANIZER_ANNOUNCED", "Announced by Bandipora District Administration and J&K Tourism.",
        "2026-08-05 to 2026-08-07", "2027-08-04 to 2027-08-06", "Bandipora District Official Portal",
        ["Jammu and Kashmir"], ["Dawar", "Gurez"], ["Dawar Ground, Gurez Valley"],
        "July to August during warm sunny mountain weather", 3,
        "Gazing at the pyramid-shaped Habba Khatoon peak, river rafting on the Kishanganga, and experiencing untouched Dardic tribal culture.",
        "6-hour mountain drive from Srinagar (125 km) via Bandipora and the high Razdan Pass (11,672 ft).",
        "Government tourist rest houses, J&K Tourism log huts, and village eco-homestays in Dawar.",
        "Border area; Indian tourists require government photo ID at check-posts; foreign tourists require permits.",
        "Respect the cultural modesty of remote villagers; ask permission before photographing tribal elders.",
        "Remote mountain valley; limited accessibility for wheelchairs.",
        "https://bandipora.nic.in",
        ["https://bandipora.nic.in", "https://www.jktourism.jk.gov.in"]
    ),
    fest(
        "fest-baisakhi-mughal-gardens", "Baisakhi at Mughal Gardens Srinagar", ["Kashmir Baisakhi Mela"],
        "Harvest & Agricultural", "Hinduism / Sikhism / Cultural",
        "Spring harvest celebration observed amidst blooming terraced fountains of Shalimar and Nishat Gardens.",
        "Dating back to the Mughal era when Jahangir and Shah Jahan laid out pleasure gardens that bloomed during Baisakhi.",
        "Celebrates the ripening of the rabi crop and the formal opening of tourist season in the Kashmir valley.",
        "Celebrates nature's abundance, water channels, and multi-faith joy in Kashmir.",
        "Living showcase of Mughal water engineering and Kashmir's secular cultural syncretism.",
        ["Community picnics under Chinar trees", "Special illumination of Mughal water cascades", "Family gatherings in Shalimar Bagh"],
        "Families lay out carpets on garden terraces, brew Kahwa on portable samovars, and celebrate spring.",
        ["Nadroo Yakhni", "Kashmiri Pulao", "Phirni", "Kulcha with Pink Tea"],
        "Brightly colored festive salwar kameez and pherans.",
        "Live Santoor, Kashmiri folk music, and children performing swings.",
        "Mughal water cascades, ancient Chinar leaves, spring flower beds.",
        "1 day", "Solar", "Celebrated on the first day of the solar month of Vaisakh (April 13 or 14).",
        "April", "SOLAR", "Mesha Sankranti solar transition.",
        "2026-04-14", "2027-04-14", "Official Solar Almanac",
        ["Jammu and Kashmir"], ["Srinagar"], ["Shalimar Bagh, Nishat Bagh, Chashme Shahi"],
        "Afternoon and evening on April 13/14", 1,
        "Lounging on lush Mughal garden lawns with water fountains sparkling, surrounded by snowy mountain peaks.",
        "Boulevard road city buses, taxis, and shikara connections.",
        "Srinagar city hotels and Dal Lake houseboats.",
        "High family footfall; orderly ticket counter queues.",
        "Do not step into historic fountains or litter garden lawns.",
        "Terraced gardens require climbing steps; lower terraces are wheelchair accessible.",
        "https://www.jktourism.jk.gov.in",
        ["https://www.jktourism.jk.gov.in"]
    ),
    fest(
        "fest-urs-shah-e-hamdan", "Urs Shah-e-Hamdan Srinagar", ["Urs Mir Sayyid Ali Hamadani"],
        "Religious - Islamic", "Islam (Sufism)",
        "The revered annual Urs of Mir Sayyid Ali Hamadani, the 14th-century Persian Sufi saint who introduced Islam and Persian arts to Kashmir.",
        "Mir Sayyid Ali Hamadani (popularly Shah-e-Hamdan) arrived in Kashmir from Hamadan, Iran, with 700 craft masters, introducing carpet weaving, pashmina, and papier-mâché.",
        "Celebrates the saint's passing (Wafat) and honors his monumental spiritual and economic contribution to Kashmir.",
        "Deep spiritual reverence across Kashmir; marks the origin of Kashmir's artisan guild traditions.",
        "Foundational cultural event in the history of Kashmiri Islam and world-renowned handicraft industries.",
        ["Recitation of Awrad-e-Fathiyya prayers", "Special congregational namaz along Jhelum riverbank", "Display of holy relics"],
        "Tens of thousands of devotees congregate at Khanqah-e-Moula on the banks of the Jhelum river, offering prayers and eating blessed halwa.",
        ["Nadir Monji", "Halwa Paratha", "Kashmiri Noon Chai", "Bakarkhani"],
        "Traditional white kurta-pyjama, skullcaps, and embroidered pherans.",
        "Spiritual Sufiana recitations, Naat, and rhythmic group dhikr.",
        "Timber pagoda spire of Khanqah, papier-mâché painted ceiling, green flags.",
        "1 to 2 days", "Lunar", "Observed on the 6th day of the Islamic lunar month of Dhu al-Hijjah.",
        "Variable (Lunar)", "LUNAR", "6th of Dhu al-Hijjah in Islamic Hijri calendar.",
        "2026-05-23", "2027-05-12", "Islamic Hijri Calendar / J&K Waqf Board",
        ["Jammu and Kashmir"], ["Srinagar"], ["Khanqah-e-Moula, Old City Srinagar"],
        "During congregational prayers on 6th Dhu al-Hijjah", 1,
        "Admiring the 1395 CE all-wood architecture of Khanqah-e-Moula without nails, soaking in profound Sufi devotion along the river Jhelum.",
        "Located in downtown Srinagar (Zaina Kadal); auto-rickshaw or walking through old city bazaars.",
        "Srinagar city hotels; limited tourist stays in downtown.",
        "Dense crowds around the shrine; modesty and patience essential.",
        "Remove footwear before entering timber shrine; head covering mandatory for all visitors.",
        "Ground floor accessible; narrow doorways inside historic shrine.",
        "https://srinagar.nic.in",
        ["https://srinagar.nic.in", "https://www.jktourism.jk.gov.in"]
    ),

    # --- LADAKH ---
    fest(
        "fest-hemis-festival", "Hemis Festival", ["Hemis Tsechu", "Hemis Monastery Festival"],
        "Religious - Buddhist", "Buddhism (Drukpa Kagyu)",
        "The grandest monastic festival in Ladakh celebrating the birth of Guru Padmasambhava with world-famous sacred Cham mask dances.",
        "Celebrated at Hemis Gompa, the wealthiest and largest monastery in Ladakh founded in 1630 by King Sengge Namgyal.",
        "Commemorates the triumph of Guru Rinpoche (Padmasambhava) over evil spirits threatening the introduction of Buddhism to the Himalayas.",
        "Believed to bestow spiritual liberation and protection from harm upon all who witness the sacred mask dances.",
        "The sacred two-storey silk Thangka of Guru Rinpoche, woven with pearls and gold thread, is unfurled once every 12 years (Monkey Year).",
        ["Unfurling of the sacred thangka in the central courtyard", "Sacred Cham dances by lamas in silk brocade and painted wooden masks", "Ritual blowing of 10-foot copper horns (dungchen)"],
        "Monastery courtyard fills with international travelers, Ladakhi villagers in traditional turquoise headwear, and meditating monks.",
        ["Gur Gur Chai (Butter Tea)", "Ladakhi Thukpa", "Skyu", "Khambir bread"],
        "Ladakhi Goncha robes with silk cummerbunds and Perak turquoise-studded headgear.",
        "Dramatic rhythmic Cham dances, cymbal clashes, and deep-toned monastic horn resonance.",
        "Wrathful wooden deity masks, prayer wheels, silk dragon banners.",
        "2 days", "Lunisolar", "Held on the 10th day (Tsechu) of the 5th month of the Tibetan Lunar Calendar.",
        "June - July", "LUNISOLAR", "Tibetan 5th Month, 10th day.",
        "2026-06-25 to 2026-06-26", "2027-07-14 to 2027-07-15", "Hemis Monastery Calendar / UT Ladakh Tourism",
        ["Ladakh"], ["Leh", "Hemis"], ["Hemis Monastery Courtyard"],
        "Morning sessions (9:00 AM to 1:00 PM) for main Cham mask performances", 2,
        "Sitting in an ancient Himalayan monastery courtyard surrounded by chanting lamas, swirling silk-brocaded masks, and mountain peaks.",
        "45 km scenic drive southeast of Leh along the Indus River via Manali-Leh Highway; shared taxis and tourist cabs readily available.",
        "Hotels and guesthouses in Leh town; homestays in Hemis village.",
        "Arrive by 7:30 AM to secure seating in the courtyard; bring sunglasses and high-SPF sunscreen for altitude.",
        "Maintain silence during sacred rituals; do not step into the central dance circle reserved for lamas.",
        "Courtyard reached by stone ramps and steps; assistance available from volunteer monks.",
        "https://ladakh.nic.in",
        ["https://ladakh.nic.in", "https://tourism.ladakh.gov.in"]
    ),
    fest(
        "fest-ladakh-festival", "Ladakh Festival", ["Leh Ladakh Tourism Festival"],
        "Traditional Fairs & Melas", "Cultural / Buddhist & Tribal",
        "A week-long celebration in Leh showcasing the diverse cultural kaleidoscope of all Ladakh communities: nomads, Dards, monks, and musicians.",
        "Inaugurated in the 1990s by Jammu and Kashmir Tourism and nurtured by the Ladakh Autonomous Hill Development Council.",
        "Celebrates the unique trans-Himalayan heritage, silk route confluence, and cultural vibrancy of high-altitude Ladakh.",
        "Unites all ethnic groups of Leh and Kargil districts before the winter snows arrive.",
        "Premier showcase for Ladakhi polo, archery, folk dances, and endangered handicraft preservation.",
        ["Grand cultural street procession through Leh Bazaar", "Traditional high-altitude Polo matches at Leh Polo Ground", "Archery contests in traditional costume", "Cham masked dances and Buddhist music exhibitions"],
        "Street carnival through ancient Leh with dancers from Zanskar, Nubra, Changthang, and Kargil dancing in vibrant regional attire.",
        ["Momos", "Tingmo with spicy dal", "Chhurpi (Yak cheese)", "Apricot juice"],
        "Gonchas, Perak headwear, sheepskin capes, and vibrant Zanskari wraps.",
        "Jabro folk dances, Shondol royal dance, and traditional Damaman drums with Surna shawms.",
        "Prayer flags across Leh Palace, wooden archery bows, yak hair tents.",
        "4 to 7 days", "Seasonal", "Held during the first week of September when autumn skies are deep azure.",
        "September", "ORGANIZER_ANNOUNCED", "Fixed by Ladakh Tourism Department (usually September 1-4).",
        "2026-09-01 to 2026-09-04", "2027-09-01 to 2027-09-04", "UT Ladakh Tourism Directorate",
        ["Ladakh"], ["Leh"], ["Leh Polo Ground, Main Bazaar, Leh Palace"],
        "Opening day parade through Leh main market", 3,
        "Watching bareback polo played at 11,500 feet altitude, seeing nomadic Changpa herders in yak wool, and sampling organic apricot delicacies.",
        "Centrally located in Leh town; walkable from most Leh guesthouses.",
        "Hundreds of hotels, boutique heritage resorts, and homestays in and around Leh.",
        "High altitude (3,500 m); ensure 48 hours acclimatization before engaging in active walking or sports.",
        "Respect local sensibilities; dress modestly.",
        "Polo ground and bazaar procession paths are flat and accessible.",
        "https://tourism.ladakh.gov.in",
        ["https://tourism.ladakh.gov.in", "https://leh.nic.in"]
    ),
    fest(
        "fest-losar-ladakh", "Losar Festival Ladakh", ["Ladakhi New Year"],
        "Regional New Year Observances", "Buddhism (Tibetan / Ladakhi)",
        "The traditional Ladakhi New Year celebrated with illuminated butter lamps, family feasts, and traditional ibex figure offerings.",
        "Dating back to the 17th-century reign of King Jamyang Namgyal who advanced the New Year celebrations before waging war against Skardu.",
        "Celebrated two months ahead of the standard Tibetan Losar due to King Jamyang Namgyal's historical military campaign.",
        "Marks the triumph of light over winter darkness, cosmic renewal, and familial reconciliation.",
        "Unique historical marker distinguishing Ladakhi calendar custom from Central Tibetan New Year.",
        ["Metho torch procession to drive out negative energies", "Illuminating houses, stupas, and shrines with butter lamps", "Exchanging traditional 'Losar La Tashi Delek' greetings", "Displaying flour and dough ibex figures for good luck"],
        "Towns and villages are illuminated with hundreds of lamps; families visit elders carrying traditional katak silk scarves and gifts.",
        ["Khapse (Fried festive pastries)", "Gutok (Sacred nine-ingredient broth)", "Chang (Fermented barley brew)", "Mutton Thukpa"],
        "New woollen Gonchas with richly embroidered borders and colorful velvet hats.",
        "Lha-rgyal victory chants, traditional flute music, and festive social circle dances.",
        "Butter lamps, flour-painted swastika floor motifs, dough ibex figures.",
        "15 days (main observances first 3 days)", "Lunisolar", "Starts on the 1st day of the 11th month of the Tibetan Lunar Calendar.",
        "December", "LUNISOLAR", "1st day of 11th month of Tibetan Calendar.",
        "2026-12-10", "2027-12-29", "Ladakh Buddhist Association Calendar",
        ["Ladakh"], ["Leh", "Kargil", "Zanskar", "Nubra"], ["Chokhang Vihara Leh, Shey Palace, village monasteries"],
        "First three days of Losar; evening torchlight procession", 3,
        "Experiencing authentic winter Ladakh, seeing Leh glowing under thousands of butter lamps in freezing sub-zero starlight, and sharing warm home hospitality.",
        "Sub-zero winter conditions; local 4x4 taxis with snow chains essential.",
        "Winter hotels with heating or cozy family homestays with bukhari woodstoves.",
        "Extreme winter temperatures (-15°C to -25°C); heavy thermal down jackets and insulated boots mandatory.",
        "Accept offerings with both hands as a mark of respect.",
        "Snow and ice on village steps; limited accessibility for mobility-impaired visitors in winter.",
        "https://tourism.ladakh.gov.in",
        ["https://tourism.ladakh.gov.in", "https://ladakh.nic.in"]
    ),
    fest(
        "fest-sindhu-darshan", "Sindhu Darshan Festival", ["Indus River Festival"],
        "Cultural Fairs & Festivals", "Cultural / National Unity",
        "Annual festival celebrated on the banks of the sacred Indus River (Sindhu) at Shey, honoring the civilizational cradle of India.",
        "Initiated in October 1997 to celebrate the Indus River as a symbol of India's unity, ancient heritage, and communal harmony.",
        "Rooted in the ancient Vedic veneration of the Sindhu River, the namesake of 'India' and 'Hindu'.",
        "Celebrates national integration, trans-Himalayan geography, and brave defense personnel guarding borders.",
        "Draws pilgrims and travelers who bring water from rivers across all Indian states to blend into the Indus River.",
        ["Blending of sacred waters brought from Indian rivers into the Sindhu", "Senior Buddhist and Hindu priests conducting joint riverside blessings", "Performances by cultural troupes from every state of India"],
        "Devotees perform morning pooja along the Shey ghats, followed by grand inter-state musical pageants under colorful Shamianas.",
        ["Ladakhi Butter Tea", "Local apricots", "North Indian satvik thali"],
        "Devotees wear traditional costumes representing their respective Indian home states.",
        "Patriotic songs, classical Indian dance recitals, and Ladakhi Buddhist ritual music.",
        "Earthen urns carrying river waters, national tricolour, prayer flags.",
        "3 days", "Lunisolar / Fixed", "Held annually on Guru Purnima (full moon of Ashadha month).",
        "June", "LUNISOLAR", "Ashadha Purnima tithi.",
        "2026-06-29 to 2026-07-01", "2027-07-18 to 2027-07-20", "Sindhu Darshan Yatra Samiti / Ministry of Tourism",
        ["Ladakh"], ["Shey", "Leh"], ["Sindhu Ghat, Shey (12 km from Leh)"],
        "Morning riverside ceremonies on Guru Purnima day", 2,
        "Pouring water from home into the mighty turquoise Indus River running through barren Himalayan gorges.",
        "Regular shuttle buses and taxis from Leh along the highway toward Hemis.",
        "Leh hotels and resorts.",
        "Sun exposure at high elevation; stay hydrated and wear wide-brimmed hats.",
        "Keep the riverbanks clean; plastic disposal strictly banned in the river.",
        "Paved riverside walkways and accessible ghat platforms at Sindhu Ghat.",
        "https://tourism.ladakh.gov.in",
        ["https://tourism.ladakh.gov.in", "https://www.incredibleindia.org"]
    ),
    fest(
        "fest-dosmoche-leh", "Dosmoche Festival", ["Festival of the Scapegoat"],
        "Religious - Buddhist", "Buddhism (Gelug / Karma Kagyu)",
        "Sacred winter festival of ritual effigies, sacred web-traps (Dosmoche), and Cham dances performed below Leh Palace to dispel bad omens.",
        "Instituted by the royal kings of Ladakh (specifically King Lhachen Gongdu) in the 14th century to protect the royal seat from natural disasters.",
        "Deeply rooted in tantric Buddhist rituals of transforming demonic negative forces into spiritual guardians.",
        "Purifies the town of ill-fortune, epidemics, and malevolent energy accumulated over the past year.",
        "Historic royal winter gathering bringing together lamas from Likir, Spituk, and Hemis monasteries.",
        ["Erection of a high wooden pole adorned with intricate sacred thread webs (Storma)", "Two days of sacred masked Cham dances in Leh courtyard", "Burning of the sacrificial effigies outside town on the second evening"],
        "Locals in fur caps pack the historic courtyard under Leh Palace, watching monks dance, followed by a ceremonial procession carrying the effigies to be burnt.",
        ["Hot Thukpa", "Khambir bread", "Yak butter tea", "Steaming momos"],
        "Heavy winter sheepskin coats, fox-fur hats, and velvet boots.",
        "Chanting of protective mantras, skull-mask dances, and dramatic drumming.",
        "Sacred thread webs, dough torma sculptures, Leh Palace walls.",
        "2 days", "Lunisolar", "Celebrated on the 28th and 29th days of the 12th Tibetan month, just before the Tibetan New Year.",
        "February", "LUNISOLAR", "Tibetan 12th Month, 28th-29th day.",
        "2026-02-15 to 2026-02-16", "2027-02-05 to 2027-02-06", "Leh Monastic Council",
        ["Ladakh"], ["Leh"], ["Courtyard below Leh Palace, Main Bazaar Leh"],
        "Afternoon sessions and second-day evening effigy burning procession", 2,
        "Witnessing raw, authentic Buddhist winter magic without tourist crowds, seeing the dramatic burning of the scapegoat effigy.",
        "Walkable within Leh old town.",
        "Winter-operational hotels and homestays with heating in Leh.",
        "Sub-zero conditions (-10°C to -15°C); bundle up in multiple thermal layers.",
        "Maintain respectful distance from monks carrying sacred sacrificial tormas.",
        "Cobbled uneven paths below Leh Palace; challenging for wheelchairs.",
        "https://tourism.ladakh.gov.in",
        ["https://tourism.ladakh.gov.in", "https://leh.nic.in"]
    ),
    fest(
        "fest-spituk-gustor", "Spituk Gustor Festival", ["Spituk Monastery Festival"],
        "Religious - Buddhist", "Buddhism (Gelugpa)",
        "Vibrant winter monastic festival of Spituk Monastery (Pethup Gompa) featuring sacred Cham dances and the unveiling of the colossal statue of Mahakala.",
        "Spituk Monastery was founded in the 11th century by Od-de, and transformed into a Yellow Hat (Gelugpa) monastery in the 15th century.",
        "Celebrates the victory of dharma over adharma and honors the ferocious protective deity Palden Lhamo and Mahakala.",
        "The fearsome face of the giant Mahakala (Kali) idol is unveiled to the public only once a year during this festival.",
        "Deeply venerated not only by Buddhists but also by Hindu soldiers of the Indian Army stationed nearby, who revere Mahakala as Kali.",
        ["Unveiling of the giant statue of Mahakala", "Dramatized Cham dance depicting the assassination of the anti-Buddhist king Langdarma", "Cutting of the sacrificial cake (Torma) by the Black Hat dancers"],
        "Devotees climb the craggy monastery hill to pray before Mahakala and watch lamas perform intricate dances wearing animal and wrathful deity masks.",
        ["Gur Gur Chai", "Mutton Skyu", "Khapse", "Sweet saffron rice"],
        "Winter Gonchas, woolen blankets, and heavy fur boots.",
        "Resonant monastic brass horns, cymbals, and tantric liturgical chants.",
        "Mahakala black masks, yellow crescent Gelugpa hats, katak scarves.",
        "2 days", "Lunisolar", "Celebrated on the 28th and 29th days of the 11th Tibetan lunar month.",
        "January", "LUNISOLAR", "Tibetan 11th Month, 28th-29th day.",
        "2026-01-16 to 2026-01-17", "2027-01-06 to 2027-01-07", "Spituk Monastery Calendar",
        ["Ladakh"], ["Spituk", "Leh"], ["Spituk Monastery (8 km from Leh)"],
        "Morning prayers and early afternoon Cham dances", 2,
        "Panoramic views of the snow-covered Indus valley and Leh airport runway from the clifftop monastery while listening to deep tantric chants.",
        "Short 15-minute taxi or local bus ride from Leh center.",
        "Winter guesthouses in Leh.",
        "Chilly hillside winds; warm windproof gloves, face masks, and thermals essential.",
        "Remove shoes inside temple sanctums; follow clockwise circumambulation (kora).",
        "Steep stone staircases ascending the hill; difficult for wheelchair users.",
        "https://tourism.ladakh.gov.in",
        ["https://tourism.ladakh.gov.in", "https://ladakh.nic.in"]
    ),
    fest(
        "fest-thiksey-gustor", "Thiksey Gustor Festival", ["Thiksey Monastery Festival"],
        "Religious - Buddhist", "Buddhism (Gelugpa)",
        "Stunning two-day monastic festival held at the 12-storey whitewashed Thiksey Monastery, resembling the Potala Palace of Lhasa.",
        "Founded in 1430 CE by Sherab Zangpo, Thiksey is among Ladakh's most prominent Gelug monasteries housing a 49-foot Maitreya Buddha statue.",
        "Commemorates the triumph of virtue over ignorance through tantric ritual enactments.",
        "Spiritual purification for the monastic community and agricultural villagers of the Indus valley.",
        "Home to one of the most strictly preserved monastic liturgical dance traditions in the trans-Himalayan world.",
        ["Early morning conch call from the monastery roof", "Enactment of the slaying of evil forces by Black Hat dancers", "Sacrificial distribution of the blessed effigy (Torma)"],
        "Crowds gather in the open tiered courtyard on the hillside, surrounded by multi-storey monastery chambers, listening to deep dungchen horn calls.",
        ["Traditional Ladakhi bread", "Butter tea", "Thukpa noodle broth", "Steamed momos"],
        "Traditional Ladakhi winter dresses and ceremonial robes.",
        "Monastic horns, cymbals, and sacred chants reverberating off mountain cliffs.",
        "Maitreya Buddha golden crown, Black Hat dancer crowns, white silk scarves.",
        "2 days", "Lunisolar", "Held on the 17th to 19th days of the 10th Tibetan lunar month.",
        "November", "LUNISOLAR", "Tibetan 10th Month, 17th-19th day.",
        "2026-11-27 to 2026-11-28", "2027-11-16 to 2027-11-17", "Thiksey Monastery Administrative Council",
        ["Ladakh"], ["Thiksey", "Leh"], ["Thiksey Monastery Courtyard (19 km south of Leh)"],
        "Morning conch blowing and courtyard dances", 2,
        "Marveling at the tiered hilltop monastery illuminated in morning light, seeing the giant Maitreya Buddha statue, and watching monks in wrathful masks.",
        "Direct taxis and frequent buses from Leh bus stand along the Leh-Manali highway.",
        "Leh hotels or Thiksey village homestays.",
        "Cold autumn/early winter temperatures; dress in warm layers.",
        "Do not touch sacred ritual musical instruments or dance costumes.",
        "Internal elevators and ramps provide access to Maitreya temple; courtyard requires steps.",
        "https://tourism.ladakh.gov.in",
        ["https://tourism.ladakh.gov.in", "https://ladakh.nic.in"]
    ),
    fest(
        "fest-yuru-kabgyat", "Yuru Kabgyat Festival", ["Lamayuru Monastery Festival"],
        "Religious - Buddhist", "Buddhism (Drikung Kagyu)",
        "Mesmerizing monastic mask dance festival celebrated against the surreal, otherworldly 'Moonland' geological formations of Lamayuru.",
        "Lamayuru Gompa is among the oldest monasteries in Ladakh, established in the 11th century by the great Indian Mahasiddha Naropa.",
        "Celebrates the teachings of Naropa and Padmasambhava, invoking deities to remove psychological and physical obstacles.",
        "Draws yogis, lay devotees, and lamas for deep meditation and blessings of longevity.",
        "Preserves the esoteric ritual dance forms of the ancient Drikung Kagyu lineage.",
        ["Chod tantric ritual dances", "Unveiling of giant thangka tapestries", "Demolition and burning of the sacrificial dough effigy"],
        "Monks in ferocious masks perform measured, hypnotic spins in the courtyard perched on the edge of dramatic eroded sandstone pinnacles.",
        ["Apricot cakes", "Ladakhi Khambir", "Skyu", "Sweet tea"],
        "Woolen Gonchas, maroon monk robes, and gold-brocaded silk sashes.",
        "Chanting of ancient Sanskrit-Tibetan mantras with large handheld frame drums.",
        "Moonland pinnacles, wooden protector masks, prayer flags.",
        "2 days", "Lunisolar", "Held on the 17th and 18th days of the 5th Tibetan lunar month.",
        "June - July", "LUNISOLAR", "Tibetan 5th Month, 17th-18th day.",
        "2026-07-02 to 2026-07-03", "2027-07-21 to 2027-07-22", "Lamayuru Monastery Calendar",
        ["Ladakh"], ["Lamayuru", "Kargil"], ["Lamayuru Monastery, Srinagar-Leh Highway"],
        "Mid-day Cham dances in the courtyard", 2,
        "Staring at the bizarre lunar landscape of Lamayuru from the monastery rooftop while hypnotic drums and horns fill the high-altitude air.",
        "Located 125 km west of Leh along the scenic Srinagar-Leh National Highway (NH-1); 3.5 hour drive.",
        "Monastery guest house and scenic village homestays in Lamayuru.",
        "High altitude (3,510 m); sunscreen and sunhat required.",
        "Maintain dignified silence in meditation caves and inner shrines.",
        "Steep stone staircases; limited accessibility for wheelchairs.",
        "https://tourism.ladakh.gov.in",
        ["https://tourism.ladakh.gov.in", "https://kargil.nic.in"]
    ),

    # --- HIMACHAL PRADESH ---
    fest(
        "fest-kullu-dussehra", "International Kullu Dussehra", ["Kullu Valley Devta Confluence"],
        "Religious - Hindu", "Hinduism (Himalayan Devta Culture)",
        "Week-long international congregation of over 300 village deities (Devtas) honoring Lord Raghunath at Dhalpur Maidan in Kullu.",
        "Commenced in 1660 CE when Raja Jagat Singh of Kullu installed the sacred idol of Lord Raghunath (Rama) to atone for a sin.",
        "Uniquely begins on Vijayadashami day when Dussehra celebrations end across the rest of India.",
        "Affirms the divine cosmic sovereignty of Lord Raghunath over all valley village deities.",
        "Declared an International Festival, preserving the ancient Himalayan palanquin procession tradition.",
        ["Grand rath yatra pulling Lord Raghunath's wooden chariot across Dhalpur Maidan", "Assembly of 300+ village devtas carried on ornate wooden palanquins", "Lankadahan ceremonial bonfire on the banks of Beas River on the final day"],
        "Villagers in colorful woolens carry swinging wooden devta palanquins accompanied by fanfare of Narsingha horns and Shehnai.",
        ["Siddu with Desi Ghee", "Himachali Dham (Chana Madra, Khatta)", "Babru (Kullu deep-fried kachori)", "Chha Gosht"],
        "Kullu woollen caps with embroidered patti, handwoven Kullu shawls, and Pattoo wraps.",
        "Nati folk dance of Kullu, beating of Dhol-Nagada, and resonant echoing of curved copper Narsinghas.",
        "Carved wooden Rath chariot, brass deity mohras (masks), colorful palanquin parasols.",
        "7 days", "Lunisolar", "Commences on Ashwin Shukla Dashami (Vijayadashami) and continues for 7 days.",
        "October", "LUNISOLAR", "Ashwin Shukla Dashami.",
        "2026-10-20 to 2026-10-26", "2027-10-10 to 2027-10-16", "Kullu District Administration / HP Tourism",
        ["Himachal Pradesh"], ["Kullu"], ["Dhalpur Maidan, Kullu"],
        "Opening day Rath Yatra and concluding Lankadahan ceremony", 3,
        "Watching hundreds of village deity palanquins dancing in unison to trumpet horns, shopping for authentic Kullu shawls and woolens.",
        "Direct flights to Bhuntar Airport (10 km); overnight Volvo buses from Delhi and Chandigarh.",
        "Hotels in Kullu town, Bhuntar, and nearby Naggar and Manali (40 km).",
        "Very heavy crowds at Dhalpur Maidan; follow police movement advisories around moving chariots.",
        "Do not touch devta palanquins without invitation from the attendant kardars (caretakers).",
        "Main Dhalpur fairgrounds are flat and wheelchair accessible.",
        "https://kulludussehra.hp.gov.in",
        ["https://kulludussehra.hp.gov.in", "https://himachaltourism.gov.in"]
    ),
    fest(
        "fest-mandi-shivratri", "International Mandi Shivratri Fair", ["Mandi Mahashivratri Mela"],
        "Religious - Hindu", "Hinduism (Shaivism)",
        "Seven-day historic fair where over 200 village deities arrive in Mandi ('Varanasi of the Hills') to pay homage to Lord Madho Rai.",
        "Instituted in 1527 CE by Raja Ajbar Sen, founder of modern Mandi, and formalized in the 17th century by Raja Suraj Sen.",
        "Raja Suraj Sen, having lost all his sons, dedicated his entire kingdom to Lord Madho Rai (Vishnu), declaring himself a servant.",
        "Celebrates the divine harmony between Shaiva and Vaishnava devta traditions.",
        "Showcase of Himalayan indigenous village democracy and oral devta oracles.",
        ["Grand Jaleb (regal procession) of devtas led by Lord Madho Rai's silver palanquin", "Night-long Shivratri vigil at Bhootnath Temple", "Devta Darbar consultations at Paddal Ground"],
        "Processions of silver-faced devta palanquins wind through stone-carved pagoda temples down to the expansive Paddal fairground.",
        ["Himachali Sepu Vadi", "Khatta Maas", "Mandi Dham", "Boondi Meetha"],
        "Mandi round caps, tweed coats, and colorful handwoven pattus.",
        "Himachali Nati, Karnal brass horn calls, and energetic drumming.",
        "Silver deity mohras (facial masks), marigold garlands, Madho Rai silver chariot.",
        "7 days", "Lunisolar", "Begins on Phalguna Krishna Chaturdashi (Maha Shivratri) and lasts seven days.",
        "February - March", "LUNISOLAR", "Phalguna Krishna Chaturdashi.",
        "2026-03-17 to 2026-03-23", "2027-03-07 to 2027-03-13", "Mandi District Administration Official Portal",
        ["Himachal Pradesh"], ["Mandi"], ["Paddal Ground, Bhootnath Temple, Beas Riverbanks"],
        "Opening and mid-week royal Jaleb processions", 3,
        "Exploring over 81 historic stone Shaivite temples, watching deity oracles speak in trance, tasting authentic Mandi Dham.",
        "Mandi is well connected along NH-21; 4 hours drive from Chandigarh (180 km).",
        "Hotels along the highway, riverfront guesthouses, and PWD rest houses in Mandi.",
        "Busy town center during processions; pedestrian zones enforced.",
        "Maintain sobriety and reverence around devta entourages.",
        "Paddal ground is flat and open; historic temples involve stone steps.",
        "https://hpmandi.nic.in",
        ["https://hpmandi.nic.in", "https://himachaltourism.gov.in"]
    ),
    fest(
        "fest-minjar-fair-chamba", "Minjar Fair Chamba", ["Chamba Minjar Mela"],
        "Traditional Fairs & Melas", "Hinduism / Cultural",
        "Historic monsoon fair in the ancient kingdom of Chamba celebrating agricultural prosperity and the tasseling of maize crops.",
        "Celebrated since 935 CE when the Raja of Chamba defeated the ruler of Trigarta (Kangra); named after 'Minjar' (silk maize tassel).",
        "Commemorates the triumph of the Chamba king and prayers to Lord Varuna (Rain God) for abundant harvests.",
        "Unites Hindu, Muslim, and Gaddi shepherd communities; the traditional Minjar tassel is crafted by Muslim artisans for the royal deity.",
        "Shining historic example of communal harmony in the Western Himalayas.",
        ["Tying the golden silk Minjar tassel to clothing", "Ceremonial procession from Akhand Chandi Palace to the Ravi River", "Floating the sacred Minjar offerings into the rushing Ravi River"],
        "Townsfolk dress in traditional chola and dorora, pin silk maize tassels to their shirts, and join the royal procession with musical bands.",
        ["Chamba Madra (Kidney beans cooked in yogurt)", "Chha Gosht", "Mittha (Sweet rice)", "Tudkiya Bhath"],
        "Gaddi Chola with black sheep-wool cord (Dora), embroidered Chamba caps.",
        "Chamba folk songs (Aenjhali and Musada), Nati dance, and Shehnai tunes.",
        "Silk and golden thread Minjar tassel, decorated coconut offerings, Ravi river waters.",
        "7 days", "Lunisolar", "Starts on the second Sunday of the Hindu month of Shravana.",
        "July - August", "LUNISOLAR", "Second Sunday of Shravana month.",
        "2026-07-26 to 2026-08-02", "2027-08-01 to 2027-08-08", "Chamba District Administration",
        ["Himachal Pradesh"], ["Chamba"], ["Chaugan Ground, Ravi Riverbanks, Chamba Town"],
        "Opening day flag hoisting and final day Ravi immersion parade", 2,
        "Watching the riverbank float ritual, shopping for GI-tagged Chamba Rumal embroidery and Chamba Chappals on the green Chaugan lawn.",
        "Chamba is 120 km from Pathankot railway station; 50 km from Dalhousie.",
        "Heritage hotels in Chamba town and hill resorts in nearby Dalhousie and Khajjiar.",
        "Monsoon season; check highway conditions between Pathankot and Chamba for landslides.",
        "Handle authentic Chamba Rumal with care; respect local royal customs.",
        "The central Chaugan ground is expansive, flat, and fully accessible.",
        "https://hpchamba.nic.in",
        ["https://hpchamba.nic.in", "https://himachaltourism.gov.in"]
    ),
    fest(
        "fest-lavi-fair-rampur", "International Lavi Fair Rampur", ["Rampur Bushahr Lavi Mela"],
        "Traditional Fairs & Melas", "Trade / Cultural",
        "Over 300-year-old historic trans-Himalayan trade fair on the banks of the Sutlej River in Rampur Bushahr.",
        "Formally established by treaty in the 17th century between Raja Kehar Singh of Bushahr and Tibet during the Mughal period.",
        "Historic barter agreement between Bushahr and Western Tibet for horse, wool, and pashmina exchange.",
        "Celebrates ancient Himalayan trade networks and winter preparedness before mountain passes froze.",
        "The oldest commercial trade fair in the Indian Himalayas, sustaining traditional Kinnauri and Spitian wool weavers.",
        ["Official inauguration with cultural display on the Sutlej riverbank", "Trading of Chamurthi cold-desert horses and Kinnauri pashmina", "Selling dry fruits (almonds, chilgoza pine nuts, walnuts) and handmade woollens"],
        "Traders from Kinnaur, Lahaul-Spiti, Kullu, and Tibet gather on the river terraces to buy, barter, and celebrate before winter sets in.",
        ["Siddu with Walnut Chutney", "Thukpa", "Chilgoza (Pine nuts)", "Kinnauri Apple Wine"],
        "Kinnauri green velvet caps (Thepang), woven Dohru shawls, and heavy silver coin necklaces.",
        "Kinnauri folk Nati, tribal pipe melodies, and energetic percussion.",
        "Sutlej River gorge, Chamurthi pack-horses, dry fruit bags.",
        "4 days", "Solar / Fixed", "Held annually from November 11 to 14.",
        "November", "FIXED", "Fixed calendar schedule November 11-14.",
        "2026-11-11 to 2026-11-14", "2027-11-11 to 2027-11-14", "Shimla District Administration",
        ["Himachal Pradesh"], ["Rampur Bushahr", "Shimla"], ["Rampur Riverfront Grounds, Sutlej Valley"],
        "November 11 to 13 during peak market barter hours", 2,
        "Buying wild Himalayan chilgoza pine nuts and pure Kinnauri woolens, watching rare high-altitude Chamurthi horses, seeing centuries of river trade alive.",
        "Located 130 km from Shimla along the Hindustan-Tibet Road (NH-5); 4-hour scenic drive.",
        "Hotels and guest houses in Rampur Bushahr and nearby Narkanda (65 km).",
        "Crisp early winter mountain chill; warm jackets and woollens required.",
        "Engage in fair bargaining with local tribal weavers and fruit farmers.",
        "River terrace market is generally flat; uneven cobblestones in traditional bazaar.",
        "https://hpshimla.nic.in",
        ["https://hpshimla.nic.in", "https://himachaltourism.gov.in"]
    ),
    fest(
        "fest-phulaich-kinnaur", "Phulaich Festival Kinnaur", ["Festival of Flowers Kinnaur", "Ookayang"],
        "Seasonal Celebrations", "Tribal / Nature",
        "Unique Himalayan flower-gathering festival celebrated in the high-altitude villages of Kinnaur to honor village deities and remember ancestors.",
        "Ancient tribal ritual observed by the indigenous Kinnaura people across centuries, synchronized with late summer alpine wildflower blooms.",
        "Young village men trek to high mountain ridges (14,000+ ft) to harvest sacred Ladra and Brahma Kamal flowers.",
        "Celebrates the transient beauty of nature, floral offerings to deities, and affectionate remembrance of departed village ancestors.",
        "Preserves ancient pre-Vedic animistic flower rites and collective village solidarity in trans-Himalayan valleys.",
        ["Youth scale dangerous alpine ridges to harvest wild flowers", "Greeting flower harvesters at village gates with drumming and wine", "Weaving floral wreaths for village deities and community ancestor shrines"],
        "Villagers dance in open circles on village grounds holding hands, wearing wreaths of wild alpine blooms, and singing ancient ballads.",
        ["Ogla and Fafra (Buckwheat cakes)", "Chulli (Wild apricot oil dishes)", "Kinnauri Apple cider (Drakht)", "Local goat meat stew"],
        "Kinnauri Thepang caps with fresh wild flowers pinned on the brim, handwoven woollen coats.",
        "Kinnauri Nati, slow circular synchronized steps, and melodic pastoral chants.",
        "Brahma Kamal, Ladra wild alpine flowers, horn trumpets.",
        "1 to 3 days per village", "Lunisolar", "Observed in the Hindu month of Bhadrapada (August-September) across different Kinnaur villages.",
        "August - September", "COMMUNITY_SPECIFIC", "Bhadrapada month; specific date varies by village council (panchayat).",
        "2026-09-12 to 2026-09-14", "2027-09-02 to 2027-09-04", "Kinnaur District Administration",
        ["Himachal Pradesh"], ["Kalpa", "Sangla", "Reckong Peo"], ["Village grounds across Sangla and Kalpa valleys"],
        "September afternoon during village circle dances", 2,
        "Witnessing high-altitude flower ceremonies, majestic views of the Kinnaur Kailash massif, and participating in warm village circle dances.",
        "Reached via NH-5 (Hindustan-Tibet Road); 230 km from Shimla.",
        "Homestays, luxury riverside camps in Sangla, and hotels in Kalpa.",
        "Mountain road subject to monsoon rockfalls; check road clearance before travel.",
        "Do not pick wild Brahma Kamal flowers yourself; they are strictly protected by forest laws.",
        "Village terrains involve sloped paths and stone steps; limited wheelchair access.",
        "https://hpkinnaur.nic.in",
        ["https://hpkinnaur.nic.in", "https://himachaltourism.gov.in"]
    ),
    fest(
        "fest-renuka-fair", "Renuka Fair", ["International Renuka Ji Fair"],
        "Religious - Hindu", "Hinduism (Vaishnavism / Mother Worship)",
        "Sacred annual fair on the banks of natural lake Renuka Ji, commemorating the divine reunion of Lord Parashurama with his mother Renuka.",
        "Deeply rooted in the Puranic tradition of Sage Jamadagni, Mata Renuka, and their incarnation son Lord Parashurama.",
        "According to legend, Lord Parashurama visits his mother annually on Devprabodhini Ekadashi to pay obeisance.",
        "Celebrates filial devotion, mother-child bonds, and natural water preservation in the Shivalik foothills.",
        "Renuka Lake is India's smallest Ramsar wetland site, revered as an embodiment of Goddess Renuka herself.",
        ["Arrival of Lord Parashurama's silver palanquin from ancient temple in Jamu Koti", "Holy dip in the calm waters of Renuka Lake at dawn", "Deepdan (floating illuminated oil lamps) on lake water"],
        "Thousands of sadhus and villagers camp along the wooded lake shores, taking holy dips, listening to sacred katha, and offering evening lamps.",
        ["Jaggery sweets", "Himachali Pakoras", "Sidu", "Kheer"],
        "Traditional Sirmauri woollen caps, colorful shawls, and dhotis.",
        "Sirmauri folk Nati, devotional bhajans, and conch fanfares.",
        "Natural outline of Renuka Lake shaped like a reclining woman, silver Parashurama palanquin, earthen lamps.",
        "5 to 6 days", "Lunisolar", "Starts on Kartika Shukla Dashami and concludes on Kartika Purnima.",
        "November", "LUNISOLAR", "Kartika Shukla Paksha Ekadashi to Purnima.",
        "2026-11-20 to 2026-11-24", "2027-11-09 to 2027-11-13", "Sirmaur District Administration",
        ["Himachal Pradesh"], ["Renuka Ji", "Nahan"], ["Renuka Lake Shore Grounds, Sirmaur"],
        "Devprabodhini Ekadashi dawn holy dip and evening lamp floating", 2,
        "Walking around the tranquil sacred lake shaped like a reclining mother, observing hundreds of floating golden lamps on dark water.",
        "Located 40 km from Nahan; 125 km from Chandigarh.",
        "HPTDC Hotel The Renuka on lake shore, pilgrim dharamshalas, and Nahan hotels.",
        "Crowded lake perimeter during full moon night; barricades along deep water zones.",
        "Do not feed artificial food to sacred fish; remove shoes near the lake ghats.",
        "Paved flat walking path surrounds the lower lake perimeter; moderately accessible.",
        "https://hpsirmaur.nic.in",
        ["https://hpsirmaur.nic.in", "https://himachaltourism.gov.in"]
    ),
    fest(
        "fest-halda-festival", "Halda Festival Lahaul", ["Lahaul Winter Flame Festival"],
        "Seasonal Celebrations", "Buddhism / Shamanic Nature",
        "Ancient winter festival of cedar torches celebrated in the snowbound valleys of Lahaul to banish dark spirits and welcome prosperity.",
        "Centuries-old pre-Buddhist tradition practiced in the Chandra and Bhaga river valleys of high-altitude Lahaul.",
        "Dedicated to Shiskar Apa, the goddess of wealth and good omen in the harsh trans-Himalayan winter.",
        "Marks the transition of winter, community unity during months of snow-isolation, and prayer for healthy crops.",
        "Fascinating living survival of ancient Bon and Himalayan fire-worship customs.",
        ["Every household prepares long cedar-wood torches (Halda)", "Lighting torches simultaneously at midnight and walking to a designated community mound", "Casting burning torches onto a collective bonfire while shouting sacred invocations"],
        "Villagers march through deep snow carrying flaming torches that cast dramatic orange shadows on frozen peaks, followed by communal dancing and feasting.",
        ["Lahauli Buckwheat roti", "Mutton broth with dried mountain herbs", "Lugri (Barley home brew)", "Sweet roasted barley flour (Tsampa)"],
        "Traditional heavy woolen robes, fur-lined coats, and woollen caps.",
        "Rhythmic foot-stomping snow dances, traditional flutes, and hand-beaten drums.",
        "Flaming cedarwood torches, community bonfires in snow, juniper sprigs.",
        "2 to 3 days", "Lunisolar", "Observed in Magha month (January-February); specific dates decided by the local Buddhist Lama of Kardang or Shashur monastery.",
        "January - February", "COMMUNITY_SPECIFIC", "Lama-designated date in Magha month.",
        "2026-01-22 to 2026-01-24", "2027-02-10 to 2027-02-12", "Lahaul & Spiti District Administration",
        ["Himachal Pradesh"], ["Keylong", "Ghar Valley", "Lahaul"], ["Villages of Gahar, Chandra, and Pattan Valleys"],
        "Midnight community torch procession in snow", 2,
        "Experiencing sub-zero winter wonderland accessible through Atal Tunnel, seeing dozens of flaming cedar torches march across white snowy slopes.",
        "Accessible from Manali via the Atal Tunnel (approx. 2 hours to Keylong); 4x4 vehicles mandatory.",
        "Winter-operational homestays and hotels in Keylong and Sissu.",
        "Extreme winter cold (-10°C to -20°C); thermal snowsuits, crampons, and snow boots essential.",
        "Do not stand close to burning cedar branches; follow community elders' directions.",
        "Deep snow and ice; limited accessibility for wheelchairs in winter.",
        "https://hplahaulspiti.nic.in",
        ["https://hplahaulspiti.nic.in", "https://himachaltourism.gov.in"]
    ),
    fest(
        "fest-himachal-day", "Himachal Day", ["Himachal State Formation Day"],
        "State Formation & Heritage Days", "Secular / Patriotic",
        "Official state commemoration celebrating the creation of Himachal Pradesh as a Chief Commissioner's province on April 15, 1948.",
        "On April 15, 1948, 30 erstwhile princely hill states were integrated to create Himachal Pradesh; full statehood attained in 1971.",
        "Marks the political birth and unification of diverse hill kingdoms into a single progressive state.",
        "Celebrates Pahari identity, democratic progress, hill agriculture, and educational achievements.",
        "State-level ceremony honoring freedom fighters, soldiers, and civil achievers.",
        ["Grand state police and cultural parade at Shimla Ridge", "Honoring distinguished citizens with state awards", "Cultural folk troupes performing from all 12 districts"],
        "Crowds gather at The Ridge in Shimla to watch the formal flag hoisting, police marching contingents, and vivid folk dance performances.",
        ["Himachali Dham", "Siddu", "Mittha", "Sepu Vadi"],
        "Pahari suits, Kullu caps, Bushahri caps with velvet borders, and tweed jackets.",
        "Statewide Nati folk dance competition, police brass band performances, and folk orchestras.",
        "State emblem, deodar tree motifs, Indian National Flag on The Ridge.",
        "1 day", "Fixed", "Celebrated annually on April 15.",
        "April", "FIXED", "Fixed calendar date April 15.",
        "2026-04-15", "2027-04-15", "Government of Himachal Pradesh Official Notification",
        ["Himachal Pradesh"], ["Shimla", "Dharamshala", "Mandi"], ["The Ridge Shimla, District Police Grounds"],
        "Morning parade (9:30 AM to 12:30 PM) on The Ridge", 1,
        "Standing on the iconic open promenade of The Ridge in Shimla enjoying festive hill dances with panoramic Himalayan views.",
        "Walkable along Mall Road Shimla; taxi services to lift base.",
        "Hotels along Mall Road, Circular Road, and Chotta Shimla.",
        "Large festive public gathering; arrive early for seating on The Ridge benches.",
        "Formal state function; stand respectfully during the National Anthem.",
        "The Ridge is a flat pedestrian esplanade with good wheelchair accessibility.",
        "https://himachal.nic.in",
        ["https://himachal.nic.in", "https://himachaltourism.gov.in"]
    )
]

print(f"Loaded Northern festivals part 1: {len(FESTIVALS_NORTH)}")
